### ISSUE TITLE
Skjule testtjenester i delegering av enkeltrettighet

### ISSUE THREAD

**Issue by hannekristin** [Altinn/altinn-access-management-frontend#1033]
![Image](https://github.com/user-attachments/assets/f4bce28a-d52f-4ad1-95f5-9e61443fd321)

Når man skal delegere en enkeltrettighet viser de 3 første sidene bare testtjenester. Dette må vi gjøre noe med.

I første omgang vil en quick fix være å hardkode frontend til å vise en gitt liste av de 10 "mest brukte" tjenestene for å skjule problemet med synlige testtjenester, noe som kan gjøres i frontend. På langsikt bør vi imidlertid få en måte å skille ut testtjenester slik at de ikke vises for enhver bruker i prod. Dette vil imidlertid kreve endringer fra Resursregisteret i tillegg til i frontend og er derfor ikke prioritert i denne omgangen.

OBS: Siden det her er snakk om en statisk liste så vil den være skreddersydd til Prod og TT02. I alle andre miljø bør vi heller alt bare vises slik det gjøres nå.

- [x] Finn ut hvilke 10 tjenester som er "mest brukt" (evt. "mest delegert"?)
- [x] Legg denne listen inn i koden som en liste med resursIDer. (I BFF eller i react? Hva er mest ryddig?)
- [x] Når paginated search kalles uten søketekst og filter (og vi er i TT02 eller prod), filtrer listen med resurser slik at kun de med ID i topp-listen blir returnert til klienten. Dersom søketekst eller filter er satt skal søket fungere som vanlig og testtjenester være inkludert
- [x] Endre i react, slik at tesksten som sier "\<tall\> treff på søket" sier "Populære tjenester" når søketekst og filter er tomt.

Liste over 10 populære tjenster:

![Image](https://github.com/user-attachments/assets/49e3d28b-caf9-4a7e-8a0c-d426dfa23bca)

```[tasklist]
### Test
- [ ] Verifisere tjenester som er mest brukt og har listet opp i lista skal dukke opp først i tt02 og prod istedenfor testtjenester

**Comment by hannekristin** [comment]
De 10 mest brukte tjenestene:
Arbeids- og Velferdsetaten (NAV)- Sykemelding - oppgi nærmeste leder
Arbeids- og Velferdsetaten (NAV)- Inntektsmelding
Skatteetaten - RF-1086 Aksjonærregisteroppgaven
Brønnøysundregistrene - RR-0002 Årsregnskap
Skatteetaten - RF-1316 Attester
Skatteetaten - RF 1306 Kontakt skatteetaten
Skatteetaten - RF-1307 Bestill elektronisk skattekort
Direktoratet for byggkvalitet - Nabovarsel
Direktoratet for byggkvalitet - Svar på nabovarsel
Statistisk Sentralbyrå (SSB) - Egenmeldt sykefravær (RA-0182)

**Comment by allinox** [comment]
@hannekristin 
Jeg har gått igjennom denne listen for å finne resurs-id for tjenestene, men det er to av dem det er litt problemer med.
- `RR-0002 Årsregnskap` finnes det 8 stykker av (jeg tror det kommer ny hvert år) så den kan vi ikke vise. Kan du komme med et annet alternativ for å erstatte denne fra listen?
- `RF 1306 Kontakt skatteetaten` har også mange varianter avh. av om man er næringsdrivende eller privatperson eller noe annet. Vet du hvilken av dem som er mest populær?

**Comment by hannekristin** [comment]
@allinox Okei. Da kan vi ta: 
Skatteetaten - A01 a-melding og kontakskjema for næringsdrivende

**Comment by allinox** [comment]
@hannekristin 
Flott! Takk for kjapt svar 😄

**Comment by hannekristin** [comment]
@acn-Sneha De skal være tilgjengelig i begge miljøene ja.

**Comment by allinox** [comment]
@acn-Sneha 
Nei, det er ikke ute i Prod enda, kun i TT02.
Det skal ut i prod denne uken, men sånn deploy-planen vår er pr nå så er det en uke imellom deploy til TT og til prod.

**Comment by acn-Sneha** [comment]
@allinox @hannekristin men jeg ser ikke de tjenester i resource lista i tt02 som listet ut her i tasken? Skal det være de som ligger her i denne tasken eller det er de tjenester som er mest brukt?

**Comment by allinox** [comment]
@acn-Sneha Det skal være de som er listet i tasken, men det er ikke lagt inn noen spesifikk sortering på dem.
Sånn det er implementert så er bare at de som er oppgitt i tasken skal trekkes ut av søket og vises i frontenden.
Hvilke er det du ikke finner i tt02? (obs: det er ikke satt opp spesielt leselig i tasken, men det er det midterste på hver linje som er navnet på resursen 😅)

**Comment by acn-Sneha** [comment]
@allinox Det var den som jeg ikke fant 
![image](https://github.com/user-attachments/assets/ed205ee9-09c7-441e-854a-41fb75abee7d)

**Comment by acn-Sneha** [comment]
@allinox Da har jeg verifisert det i prod og ser greit ut nå. Godt arbeid :)
