### ISSUE TITLE
Upgrade to newest version of Designsystemet

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#1071]
# Description
https://github.com/digdir/designsystemet

Recently, Designsystemet has begun releasing pre-releases of their upcoming v1 on the form `v1.0.0-next.X`. This change in format means they go ignored by our renovate bot for automatic patching, and we have thus been stagnant on version `0.63.0`.

In the interest of scoping out and possibly lessen the work on going over to v1, we want to attempt a migration to this prerelease series. (Unless doing so proves to be too much work for this time being)

# To do's

Switch to the newest release of Designsystemet, note the size of the work needed to fix the breaking changes and, if they are managable, do these fixes in order to proceed using the v1 pre-release

Things to consider when updating (keep in mind, there might be more):
- [ ] Tokens have likely changed names, so go through them and make sure to switch to the new standard
- [ ] Sizes on components
- [ ] Changes to other props
- [ ] Local components in our repo that uses design system components might be broken by things like changes in padding. Pay extra attention to these components:
  - [ ] Filter
  - [ ] ActionBar 
- [ ] Run the frontend and check all pages for visual changes from the current version in TT02. Does everything look the same?
  - [ ] This will require manual testing

OBS: Designsystemet runs through our entire solution, especially for the code that is currently in production. Therefore, it is important to be thorough.

**Comment by sonwit** [comment]
A quick test on updating to latest version (1.0.0-next.32) 

![Skjermbilde 2024-09-17 kl  09 07 55](https://github.com/user-a
![Skjermbilde 2024-09-17 kl  09 10 41](https://github.com/user-attachments/assets/7d4a0c92-2ee2-4a28-a739-ffac8ec8f7a4)
ttachments/assets/c1eabe71-b9e1-4106-a367-0afe4996d134)
![Skjermbilde 2024-09-17 kl  09 08 03](https://github.com/user-attachments/assets/fe4f6e23-7e21-4b7c-8f0a-f835b1ee2023)

**Comment by allinox** [comment]
@sonwit 

Yeah... that wasn't pretty 😅
But it might not all be because of breaking changes.

I suppose you've already run yarn?
I forgot to mention it before, but the Design system can be a bit unwieldy when updating - especially on Windows and with VS Code.
Sometimes you have to delete the yarn_lock file and the node modules folder manually and then run yarn again to get the actual new packages installed. I don't know why exactly, but it has been an issue in the past.

**Comment by sonwit** [comment]
Avklaring: Vi prøver å bruke samme fargene som i dag i eksisterende ting i prod i dag. Ellers avventer vi beslutning om farger/brand på altinn-nivå.
