### ISSUE TITLE
Få e2e-tester til å kjøre i TT02

### ISSUE THREAD

**Issue by Nyeng** [Altinn/altinn-access-management-frontend#1088]
# Beskrivelse
E2E-testene blokkeres av captcha-mekanisme i importen, vi må undersøke og se hva vi kan gjøre for å omgå denne for å få testene til å kjøre i tt02 som er et viktig testmiljø brukt av eksterne. 

Diskusjon rundt tt02 fra Slack:
https://digdir.slack.com/archives/C079T644HQE/p1726049719832709

"Henning Normann" har visst peil på TT02 og vet kanskje hva som skal til. 

# To do's

- [ ] Hent inn info om tt02-innlogging 
- [ ] Gjør fiks

**Comment by Siri-Anna** [comment]
@Nyeng er dette fortsatt blokkert? Eller har vi ny status? :)

**Comment by sneha-sirure** [comment]
@Nyeng @Siri-Anna Det er QueueIT (QueueIT er en køløsning som vil plassere brukere i kø ved stor belastning, typisk under skatteoppgjørsperioden. Dette har vært for å beskytte IdPorten mot for mye trafikk) som er nå har vi skrudd av denne i tt02 som gir ikke noe captcha feil i tt02. Da lukker jeg tasken.
