### ISSUE TITLE
Lage ListItem komponent

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#1111]
![Image](https://github.com/user-attachments/assets/dcde7e61-36ef-41ef-bed0-c9b856fe299d)

# Beskrivelse

Lister skal vises på lik måte på tvers av Autorisasjon og Innboks, og en felles ListItem komponent skal deles mellom våre to repoer.
Selv om dette nye delings-repoet ikke er helt i gang enda har vi avtalt med Arbeidsflate om at vi på Autorisasjon kan begynne på implementasjonen av denne ListeItem-komponenten hos oss siden vi er de som har mest bruk for den.

## Figma
https://www.figma.com/design/5skVNCuvMaDdmXcbRZQ9w6/TT02---UI-komponenter?node-id=19-8865&node-type=canvas&t=8JKXk8DNMkf1S4dF-0

# To do's

Lag listItem-komponenten
- [ ] Size: lg, md, sm
- [ ] Icon
- [ ] Title
- [ ] Subtitle
- [ ] Action(s) (Eks. knapp. Skal være plassert til høyre)
- [ ] Hele Itemet skal kunne være klikk-bart dersom en onClick er gitt. Den må da ha en hover og active state med tilhørende farger
- [ ] Skal den være expandable?
- [ ] Skal være navigerbar med tastatur
- [ ] Modus for spacing mellom Items (for bruk på farget bakgrunn) og for separering kun med linje mellom elementer (for bruk på hvit bakgrunn, eks. i modaler)

Vis ListItem-komponenten i Storybook
- [ ] Lag story med eksempler og visning av props

Lag komponetteste?
- [ ] Lag komponenttester for å teste komponenten
  - I cypress? Playwright? Annet verktøy som skal brukes i nytt komponent-repo??

**Comment by sonwit** [comment]
Denne er allerede løst av arbeidsflate i altinn-components biblioteket, markerer den derfor som done!
