### ISSUE TITLE
Design av delegering av enkeltrettigheter som React-komponent i Altinn 3

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-access-management-frontend#114]
Delegering av  enkeltrettigheter skal utvikles som ny React komponent i Altinn 3. 
I design av dette har vi 2 alternativ: 

1. bygge design videre på det som er utviklet for delegerbare API ressurser
2. starte på nytt design utformet i kontekst av NØTT for delegering av enkelttjenester

Konklusjon er at vi ønsker å gå for alternativ 2 hvor vi utvikler ny React-komponent for delegering av enkelt tjenester med utgangspunkt i arbeid som er gjort i NØTT. 

Arbeid videre: 

- [x] Evalurere tilbakemeldinger fra brukertest på skisse for enkeltdelegering i NØTT
- [x] Justere skisser i forhold til tilbakemeldinger
- [x] Lage skisse for ekspandering av tjeneste når man klikker på "legg til tjeneste" (se liste over nødvendig funksjonalitet nedenfor)
- [x] Vurdere om man trenger en "oppsummering/kvitteringsside" når man er ferdig med delegering av enkelttjenester. 
- [x] Vurdere hvor/hvordan man skal komme tilbake til profil i Altinn 2
- [x] Vurdere hva som skal lages i Design system og hva som lages som "lokal komponent for autorisasjon"
- [x] Planlegge eventuelle oppgaver for implementering i Designsystem/ Access-management-frontend

Skisser under arbeid i figma ligger her: (https://www.figma.com/file/ESobgAq072y7eQa4gP1JCKER/Profil?node-id=6723%3A92391&t=iIqgqehA9CaqjI7N-1)

Arbeidet er også relevant for GUI som skal lages for å be om rettighet til enkelt tjeneste, se issue <opprett issue og lenke til>

Denne visningen vil være i A2. 
![image](https://github.com/Altinn/altinn-access-management-frontend/assets/25847572/7d33cc02-cd8e-49bd-8ca5-a8350abc12c9)

Når man klikker på gi tilgang til enkelttjenester så skal ny React-komponent åpnes: 
Foreløpig skisser ser slik ut:  
![image](https://github.com/Altinn/altinn-access-management-frontend/assets/25847572/7661bff8-ea70-4365-8945-3296ca01ba26)

- Man kan søke etter all tekst som vises frem (tjenestenavn, tjenesteeiernavn, beskrivelse)
- Listen etter søk sorteres etter mest relevante tjenester i forhold til søk 
- Filtrer på etat gir mulighet til å begrense søk til tjenester som eies av angitte tjenesteeiere
- Det vil ikke være mulig å filtrere på kategori da vi fortsatt ikke har metadata på tilstrekkelig mange nok tjenester/ressurser til at det gir verdi
- [x] Det må vurderes om "mest brukte" skal tilbys på samme måte som i dag eller om man skal vente til man har bestemt seg for hvilke kriterier som skal ligge til grunn for dette. I dag får man opp en liste over de tjenester i Altinn 2 som avgiver har instansiert mest. Det betyr at man f eks ikke får med A3 apper, lenketjenester, osv i den listen.  
- I app policy så kan det være delegert rettigheter til en org - f eks SKE får lese data fra API, SKE får instansiere opp et skjema. Disse reglene bør ikke slå inn når man forsøker å delegere en enkeltrettighet
- Tjenester som er ikke delegerbar eller som styres av RRR bør ikke listes ut med mindre bruker søker spesifikt etter denne. 
- Beslutning: Siden det ikke er mulig å hente ut mes brukte både fra 2.0. og 3.0 skal det presenteres en alfabetisk liste. På Mobil view er det tomt når man kommer inn.

![image](https://user-images.githubusercontent.com/25847572/222705451-ccf464c4-1aea-4d38-aed5-bfaf156b96ec.png)
- valgte tjenester hopper opp som "valgt"
- ved ekspandering av tjeneste vises hvilke operasjoner på tjenesten en delegering gir tilgang til
- hvis man ikke har rettighet til å delegere noen av operasjonenen så markeres tjenesten gult med forklaringstekst
- [ ] tilbakemelding fra brukere tilsier at de ikke helt forstår hva de har og ikke har. Må vurdere om det er mulig å justere skissen slik at de blir lettere å forstå

![image](https://user-images.githubusercontent.com/25847572/222705934-0a6c1ece-e508-4096-afca-a0a336c1958d.png)

- hvis man ikke har mulighet til å delegere tjenesten overhodet markeres den som rød
- Forklaringer som tilbys i dag fungerer dårlig i brukertest. Kan dette gjøres bedre? Kan vi forklare bedre hvorfor tjenesten ikke kan delegeres av bruker? 

![image](https://user-images.githubusercontent.com/25847572/222706261-6cbaa53e-91d4-43f3-b519-0e8f66655363.png)
- kvitteringsside skal vises når man er ferdig

### Nødvendig funksjonalitet ved ekspandering av tjeneste når man klikker på "legg til tjeneste"
- Alle operasjoner som knyttet til ressursen skal vises. 
- Det kan være ulike operasjoner knyttet til ulike steg. @jonkjetiloye lager eksempel på "rettigheter" som returneres fra kall som gjøre mot "ett eller annet api" (se eksempel nedenfor)
- Alle operasjoner (som tilgangsstyrer kan delegere) skal være valgt. 
- Operasjoner som ikke kan delegeres skal vises, men det må være tydelig at de ikke er delegerbare. 
- Det må være mulig for tilgangsstyrer å "velge bort" en eller flere operasjoner som man ikke ønsker å delegere. OBS! Les-operasjon vil ofte være en forutsetning for å kunne utføre andre operasjoner, f eks kunne "signere"
- Det bør være en knapp for å bekrefte at man gir de operasjoner som er valgt i ekspanderingsfelt. Først når den er valgt skal delegering foregå. 

Relatert issu er https://github.com/Altinn/altinn-authorization/issues/142

**Comment by jonkjetiloye** [comment]
Her er ett eksempel av alle individuelt delegerbare rettigheter knytt til BRG appen "Registrering av reelle rettighetshavere"
![image](https://user-images.githubusercontent.com/40996230/215150647-9477a6f3-767a-4a20-80b3-3ad9132b4956.png)

**Comment by annerisbakk** [comment]
Settes til blocked i påvente av nye komponenter i Figma designsystem

**Comment by sivaglen** [comment]
@hannekristin og @annerisbakk -  Må man ha nye komponenter i Figma for å ferdigstille denne? 
 I mitt hode handler denne oppgaven handler om å komme frem til et forslag til design tegnet i Figma som vi så skal bruke for å planlegge videre oppgaver (se tasklist)

**Comment by hannekristin** [comment]
@sivaglen Nei vi trenger ikke det, vi bare venter på noe for å få det helt rett. Vi har gått gjennom skissene med frontend og designteam så det arbeidet er i gang. Satte den til block så den ikke skulle ligge i boardet frem til vi får brukertestet det. Vi lager forresten prototype nå.

**Comment by allinox** [comment]
Lukker denne da funksjonaliteten nå er implementert og levert
