### ISSUE TITLE
Update axios calls to use cookie values

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#117]
Currently axios calls doesn't use cookie values. This task is about updating all those calls to make them use cookie values.

Tasks: 

- [x] Find a way to get cookies.
- [x] update axios calls to use cookies in order to do axios calls.

AC:

- Check if returned data corresponds to the data that's expected to be returned.

**Comment by sivaglen** [comment]
@Albertlarsen trenger vi dette for å ferdigstille delegerbare API ressurser?

**Comment by Albertlarsen** [comment]
@sivaglen Ja men det tar ikke lang tid
