### ISSUE TITLE
Long continous text solution for components

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#119]
Long continuous texts created below problem in picture for us in Accordions. This task is about making a solution for this.

Additional info:

- This character may be used to conditionally split words: Soft Hyphen U+00ad.

Tasks:
- [ ] Find out how to insert soft hyphens in text from database in bff
- [ ] Make accordion react to special characters the same way it reacts to soft hyphens.

AC:

- Long continous texts doesn't make components take up more space than set.

Design review:

1. Gå til https://am.ui.at23.altinn.cloud/accessmanagement/ui/offered-api-delegations/choose-api og se på det lengste sammenhengende api-navnet om det blir splittet over flere linjer.

<img width="745" alt="image" src="https://user-images.githubusercontent.com/31471142/215794841-a663855f-720b-4db4-84b2-5a20b9c265e1.png">

**Comment by Randiabs** [comment]
så veldig greit ut. Sjekket og satt til test
