### ISSUE TITLE
Replace the hardcoded reportee with the actual reportee

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-access-management-frontend#122]
### Description

Currently, a hardcoded reportee is sent to the backend api. Replace this to use the logged in reportee

### Tasks

- [ ] Get the logged in partyid from cookie? and forward it to backend

### Acceptance Criterias
- [ ] Logged in /chosen reportee details must be presented

**Comment by Albertlarsen** [comment]
@acn-dgopa I think we've already made the frontend get the value from cookie but the cookie has http only flag. See code below. Which endpoint is this related to?


![Image](https://user-images.githubusercontent.com/31471142/217846830-87ee95d4-6d82-4d3d-a062-94156e24f9b9.png)


![Image](https://user-images.githubusercontent.com/31471142/217847104-a43f8c49-241e-4b2d-9a4d-332301a4e226.png)

**Comment by Albertlarsen** [comment]
@acn-dgopa or is this issue written for bff?

**Comment by acn-dgopa** [comment]
@Albertlarsen i actually created this for frontend. I was not aware that it was already implemented. And FYI, I had made it possible to read the AltinnPartyId cookie now. It should be available in the current test environment (ATxx). This can be closed when already implemented

**Comment by Albertlarsen** [comment]
@acn-dgopa Allright, nice of you to think of it :) Closing this then
