### ISSUE TITLE
Gi og fjerne rettigher - nødvendige endringer i rolledelegering (GUI) for å støtte migrering av lenketjeneste

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-access-management-frontend#133]
Roller i view nedenfor hentes fra A2
- antar at man ikke trenger å endre denne visningen.
- [ ]  Verifiser at denne hypotesen er riktig

![image](https://user-images.githubusercontent.com/25847572/217813765-0f557eaf-25e3-4305-88fa-d2a999aede5e.png)

Når man klikker på ? (se bilde over) så må man vise tjenester i A2 som er knyttet til rollen (slik som idag) + alle ressurser i A3 som har rollen som en del av sin delegationpolicy

- Man må hente ut ressurser fra A3 som har en definert gjeldende A2 rolle i sin ressurs-policy. 
     - Det vil være tungt å skulle hente ut informasjon fra alle policyer for alle ressurser hver gang
    - Det bør vurderes om man skal lage en egen database (e.l) som har en slik oversikt og en jobb som med jevne mellomrom sjekker om det er gjort endringer i policyer og oppdaterer en ferdig oversikt som GUI kan spørre mot
    - En slik oversikt vil antagelig også være nyttig for eksterne å spørre mot
     - Et slik oversikt vil også kunne anvendes i f eks GETROLES for Tjenesteeier når man skal sjekke om en tjnesteeier har "tjenstlig behov" for å hente ut rolle/tilgangsgruppeinformasjon om bruker for avgiver. Tjenesteier skal (iflge jurist) bare få hente ut informason om rolle/tilgangsgruppe en bruker såfremt rollen/tilgangsgruppen benytter rollen/tilgangsgruppen på deres tjenester (da har de "tjenstlig behov") 
     - [x] lager en issue til Tilgngsinfo på dette da problemstillingen hører under ressursregisteret: https://github.com/Altinn/altinn-resource-registry/issues/109
- I tillegg må man kunne hente ut alle tjenester i A2 som bruker gjeldende rolle som rollekrav 

- [ ]  Det må vurderes om visningen nedenfor skal videreutvikles i Altinn 2 - eller om den skal utvikles som en ny visning (som bruker sendes til). 
- [ ] Denne visningen burde strengt tatt vært tilgjengelig for alle - også de som ikke er innlogget. Vurder om dette er mulig

![image](https://user-images.githubusercontent.com/25847572/217814009-6dd266cb-1a8f-40a2-a1dc-1afc5022f049.png)

**Comment by Albertlarsen** [comment]
@rtafj har opprettet issue i 2.0-boardet https://dev.azure.com/digdir/Altinn/_workitems/edit/63803
