### ISSUE TITLE
Make access management use Spinner.

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#137]
Change all places where it says 'loading...' to use digdir ds' Spinner instead.

Pages that need spinners:

- [x] Overview offered
- [x] Overview received
- [x] Choose org
- [x] Choose api
- [x] Confirmation page? (Small one by the confirm button?)

AC:

- It's shown a spinner whenever a page is loading.

**Design review**

1. Gå til alle sidene som har med API-delegering å gjøre.

**Comment by Randiabs** [comment]
Design review ok, satt til test
