### ISSUE TITLE
Analyse - nødvendige endringer i GUI for å se forespørsler virksomheten har fått (migrering lenketjenester)

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-access-management-frontend#139]
Det skal utvikles funksjonalitet for å be om rettighet til ressurser (og evt apps) i Altinn 3
- antar det ikke medfører behov for endringer i GUI men at man må lage en tjeneste som henter inn opplysninger om forespørsler som ligger i A3 og vise navn på aktør som ber om rettighet i listen nedenfor (i tillegg til de man allerede henter fra A2) 
- 

- [x] Avklar hvilke endringer som må gjøres for å vise forespørsler registert i både A2 og A3

![Image](https://user-images.githubusercontent.com/25847572/218153847-d415387e-a063-4ad0-ad1a-e473948584e2.png)

**Comment by Albertlarsen** [comment]
@sivaglen Hvilke personer er tiltenkt å skulle løse disse oppgavene? 😄

**Comment by sivaglen** [comment]
Det er laget skisser for å å se forespørsel og vi har laget ny oppgave for å lage løsningsforslag. Denne lukkes
