### ISSUE TITLE
ActionBar icon isn't placed at the end

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#156]
### Description of the bug

The plus-button isn't at the end of the action bar as in the picture below. It should be at the end. To achieve this use css: 

- display: flex
- justify-content: flex-end

![image](https://user-images.githubusercontent.com/31471142/220285267-dc2e04a5-cbf8-44a8-8eeb-a7da3b1319cb.png)

### Steps To Reproduce

1. Go to accessmanagement/ui/given-api-delegations/choose-org
2. Search for an org
3. The plus-button isn't at the end of the action bar

**Comment by sivaglen** [comment]
@Albertlarsen er dette need eller wants i forhold til å migrere Delegerbare API ressurser?

**Comment by Albertlarsen** [comment]
@sivaglen er bare en liten Wants-oppgave
