### ISSUE TITLE
Delete call doesn't work

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#213]
### Description of the bug

When trying to delete. The call gets success 200 but the api-delegation isn't actually deleted.

### Steps To Reproduce

1. Go to: https://am.ui.at23.altinn.cloud/accessmanagement/ui/offered-api-delegations/overview
2. Click edit accesses
3. Delete an api-delegation
4. Click save
5. The delegation is temporarily deleted
6. Refresh page
7. The delegation is still there.

**Comment by acn-dgopa** [comment]
The delete endpoints were not deployed to at23. It is now deployed and working. @Albertlarsen You can test now

**Comment by Albertlarsen** [comment]
Yes I just tested it and it works, good work @acn-dgopa 😊
