### ISSUE TITLE
Findings from designReview of API delegation

### ISSUE THREAD

**Issue by hannekristin** [Altinn/altinn-access-management-frontend#226]
Bugs og funn fra review

**Comment by hannekristin** [comment]
Vi skal bruke Inter font https://www.figma.com/file/eeznFkuH7UletQmhN174VR/Felles---Design-Tokens?node-id=15%3A98&t=l7XpdviZp8USiE9P-1

**Comment by Albertlarsen** [comment]
@hannekristin Men design-systemet har jo ikke gått over til Inter. Så å endre til Inter burde vel skje på samme tidspunkt som de gjør det så det ikke eksisterer to ulike fonter i access management?

**Comment by hannekristin** [comment]
Jeg trodde de hadde gått over til Inter. Jeg spurte senest i dag på møtet. I dagens altinn 2 løsning bruker vi Altinn Din font, men vi skal vel over til nytt på alt.
