### ISSUE TITLE
Create component ActionBar

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#230]
### Description

**Description**
You are tasked with creating a React component called ActionBar.

Copy the accordion component from digdir design system and make some adjustments to the api and design to comply with picture below.

Tasks: 

- [x] Change name from Accordion to ActionBar on everything
- [x] Add colors for ActionBarHeader
- [x] Implement colors for ActionBarContent
- [x] Style component
- [x] Adjust chevron margins
- [x] Change chevron rotation
- [x] Add hover styling
- [x] Redo title prop
- [x] Adjust vertical margins for HeaderTexts with title and without subtitle
- [x] Redo design after discussion
- [x] Change title API
- [x] Add middle text prop
- [x] Make chevron hideable
- [x] Unify separate components
- [x] Add mouse clicker symbol on hover when ActionBar is expandable
- [x] Make action-buttons take up as little height as possible
- [x] Replace non-expandable ActionBar component in ChooseOrgPage
- [x] Replace Accordions in OverviewPage
- [x] Write tests
- [x] Make ChooseApiPage use DelegationActionBar.

**AC**
- There exists cypress tests testing the component
- It should not be expandable when ActionBar doesn't have children
- Should not show v-symbol when AccordionContent isn't set.
- Should be wcag compliant
- Should have different colors
- Should comply with design in picture below
- Should make css line break for long continous words

**Design review**
- Se på alle sidene som brukte accodion om de nye ActionBarene tilfredstiller designet.

![Image](https://user-images.githubusercontent.com/31471142/233661700-2439b7f5-7c2d-47f6-a490-ecac5d5a9f62.png)

### Additional Information
- Figmalenke: https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/Felles-komponenter?node-id=6632-30965&t=I2supNBdx8fKxsvq-0

_No response_

**Comment by hannekristin** [comment]
ActionBar mangler kant på høyresiden i den grå varianten. Dette gjelder bare på den siden der du legger til API. Ellers ser det veldig bra ut.
![image](https://github.com/Altinn/altinn-access-management-frontend/assets/103100644/1f359752-4c4a-4194-903e-21f58cd2fc42)

**Comment by Albertlarsen** [comment]
Fant en bug: 

![Image](https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/2cbe5552-9625-4359-8cb9-053194333a31)

**Comment by Albertlarsen** [comment]
Nå skal dette være fikset
