### ISSUE TITLE
Move i18 cookie set to BFF backend

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-access-management-frontend#239]
### Description

Currently we call profile from Frontend to get the language code.

We need to do this from index in BFF controller so the cookie is set before react is loaded

### Additional Information

This is related to https://github.com/Altinn/altinn-authorization/issues/287

### Tasks

- [x] Call profile from home controller and set i18 cookie (verify name and language code to use with @Albertlarsen ) 

### Acceptance Criterias
- [ ] Verify in browser that i18 cookie is set with user's preferred language

_No response_

**Comment by Albertlarsen** [comment]
Cookie name is i18next and it should be based on current language and set to 'en', 'no_nn' or 'no_nb' if possible.
