### ISSUE TITLE
Pagination Component | FDS

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#240]
### Description

Dette er en Felles Design System task hvor den speccede tasken kan bli funnet her: https://github.com/orgs/digdir/projects/3/views/1?filterQuery=pagination&pane=issue&itemId=30636600

Foreslåtte props:

- variant: 'normal' | 'compact';
- previousLabel: 'string';
- nextLabel: 'string';
- size: 'small' | 'medium'; (en fast størrelse på small og en fast størrelse på medium, ikke width 100%) 

### Additional info
-Bruk FDS sine knapper som knapper for sidetallene, forrige og neste-knappene

Se figma skisser her (Skissene er fasit på alt av button size, komponent size, etc.): https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/Felles-komponenter?type=design&node-id=16500-50762&t=9zHZrtQXg4ZGaK0K-0

![Image](https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/49340cb7-a7d1-471a-84a5-9cde826fd3cb)

**Comment by sivaglen** [comment]
@allinox - er dette en komponent som lages i felles design system?

**Comment by allinox** [comment]
@sivaglen 

Det stemmer ja 😊
