### ISSUE TITLE
Page icon gets really small

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#242]
### Description of the bug

Dummy task for fixing Page icon in altinn design system: https://github.com/Altinn/altinn-design-system/issues/286

### Steps To Reproduce

1. Go to a Page with much text and scale it down to mobile size.

**Comment by Randiabs** [comment]
Hvis man går på mottatte Api tilganger, så blir ikonet fremdeles veldig lite i mobil visning. Se bilde: 
Ellers ser det ut til at ikonet fungerer med rikitg size.


![Image](https://user-images.githubusercontent.com/94835837/228501861-4a5cbb5f-e318-4840-ad16-ff5ba403d61e.png)

**Comment by hannekristin** [comment]
Ikonet er testet ok

**Comment by Albertlarsen** [comment]
@Randiabs En liten glipp der at alle andre sider enn denne har fått fiksen, dette kommer inn sammen med en annen endring fortløpende. Sier fra når det er fikset
