### ISSUE TITLE
Lag ny ErrorSite

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#25]
The ErrorPage component in frontend looks like in the picture at the bottom because we haven't had time to work with it yet. This task consist of improving the ErrorPage. The issue gives room for free creativity but it can be wise to consolidate with the rest of Altinn. Also implement responsive design on the component.
 
**Additional info:**
We follow the design system's px-definitions on screen sizes for responsive design: 
- xs: 315-576 px.
- sm: 576-768 px.
- md: 768-992 px.
- lg: 992px and up.

Tasks:

- [ ] Display type of error.
- [x] Talk to UX about if there are any contraints on how the page should look.
- [x] Localize texts for all languages.
- [x] Responsive design is implemented on the error page

AC:
- Text is localized.
- Responsive design is implemented on the component.
- The type of error is displayed.

Forslag:

![Image](https://user-images.githubusercontent.com/103100644/213449797-f721baff-e147-4672-9dbd-0293afa93a02.png)

Lenke til Figma: https://www.figma.com/file/ESobgAq072y7eQa4gP1JCKER/Profil?node-id=6508%3A82459&t=U9Ukp4A4KKp0b2yu-1

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/31471142/203768802-80ef1ed8-649b-4c9f-b37f-26ce3ed67fbd.png">

**Comment by Albertlarsen** [comment]
@sivaglen Nei vi får bare en litt dårlig error site(Den nederste av error sitene i tasken her) hvis vi ikke gjør den før produksjon

**Comment by Torgeir333** [comment]
@sivaglen Det er heller ikke sånn at "en dårlig error site" under her er eneste alternativ. Vi har også vært innom en mulig (inkrementell) forbedring, jmf. den Slack-tråden vi hadde, som altså så sånn ut:

<img width="832" alt="ErrorPage_issue25_Skjermbilde_110123" src="https://user-images.githubusercontent.com/94476391/216617899-a20dff4f-8c8a-4e58-9934-2fe866849fc9.png">

**Comment by Albertlarsen** [comment]
@hannekristin Hvordan går error pagen Torgeir har progget opp overens med designet dere har tegnet?

**Comment by Torgeir333** [comment]
Her er en foreløpig versjon av feilsiden, per 09.02.23

<img width="567" alt="issue25_ErrorPage_kodet_per_090223" src="https://user-images.githubusercontent.com/94476391/217826373-fc37f8b9-93a6-4600-a1b2-79a2dcdf04bd.png">

**Comment by Albertlarsen** [comment]
Dette er en stor forbedring! Bra jobba @Torgeir333 :)

**Comment by Torgeir333** [comment]
Her er mobil responsiv side (mindre enn 576px, også kalt Android Small skisse)

<img width="227" alt="issue25_ErrorPage_kodet_mobilBredde_per_090223" src="https://user-images.githubusercontent.com/94476391/217831109-cc4b70c4-4089-4c21-a893-e006c66bf856.png">

**Comment by hannekristin** [comment]
Det ser bra ut. Kunne kanskje kuttet teksten i lenken til innboks til bare "Gå til innboks", og brukt mindre font på body?

**Comment by Torgeir333** [comment]
Da er landsmaal, riksmaal og anglo-amerikansk satt i språkfiler. 

@hannekristin Skal se på brødtekst-font-størrelse i mobil-versjon OK.

**Comment by Torgeir333** [comment]
@hannekristin Her er brødtekst endret fra 24px til 18px

<img width="227" alt="issue25_ErrorPage_mobil_mindreFont_100223" src="https://user-images.githubusercontent.com/94476391/218070882-f6e8488b-2811-4b96-9cad-c7857a561a8c.png">

**Comment by Torgeir333** [comment]
Her er da ErrorPage med <div> som html element.

<img width="820" alt="ErrorPage_issue25_divisentrisk_160223" src="https://user-images.githubusercontent.com/94476391/219366685-8e0644b6-56e5-493f-af72-22128f39dcba.png">

Jeg legger også ved inspector screenshot av den vakre </div> rekken, 
slik at vi dokumenterer at ingen eksotiske html elementer er blitt brukt :-D

<img width="232" alt="divisentrisk_verdensbilde" src="https://user-images.githubusercontent.com/94476391/219366862-bc225680-7494-496f-97b6-67575f7bf32b.png">

**Comment by hannekristin** [comment]
Design review ok. Setter den til test. (Antar at lenkene blir riktige etter hvert @Torgeir333 ?)
