### ISSUE TITLE
Bestemme en passende bakgrunnsfarge for Altinn 3 GUI.

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#255]
Det blir brukt en veldig neon-blå bakgrunnsfarge ved siden av Pagene i arbeidsprosessene idag som er vanskelig å få til å bestå wcag-krav. Vi måtte nylig bytte ut x-knappen fra å være hvit til å bli blå for å bestå wcag-krav.

Mulige løsninger:

- Vi kan teste ut forskjellige bakgrunnsfarger og se hvilken som fungerer best.
- Vi kan henvende oss til brukerne våre og få tilbakemelding om hvilken bakgrunnsfarge de foretrekker.
- Vi kan undersøke andre lignende applikasjoner og se hvilken bakgrunnsfarge de bruker.

AC:
- Det bør bli valgt en farge som er lettere å finne forgunnsfarger til som kan bestå wcag-krav.

**Additional info**
Jeg foreslår at det åpnes en diskusjon for mulige løsninger. Vi kan deretter velge en farge og implementere den i GUIen vår.

Jeg vil også anbefale å inkludere brukere og interessenter i diskusjonen vår. Dette vil gi oss verdifulle tilbakemeldinger og hjelpe oss med å ta en informert beslutning.

Dette er bakgrunnsfargen vi vil endre fra:
![image](https://user-images.githubusercontent.com/31471142/228212049-c268a307-27ae-4fae-8fd0-52b91cbd4e18.png)

**Comment by hannekristin** [comment]
Etter diskusjon med designsystem-gjengen velger vi å ikke endre bakgrunnsfarge nå. Dette vil komme når vi lanseres NØTT. For at kontrasten skal bli godkjent kan vi lage krysset slik: 
![image](https://user-images.githubusercontent.com/103100644/228477864-1ba72eec-0aca-48c2-9edd-a98eca2ed380.png)
