### ISSUE TITLE
Restructuring of receipt page

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#276]
### Description

The receipt page is somewhat messy in it's current state. To address this concern, new sketches have been made.

These changes need to be implemented:
- [x] Order of delegations: Sort the delegations so that they are presented in alphabetical order by recipient name
- [x] List-layout: On small screens, the name of the recipient should be presented as a title in each list item, while the api should be the subtitle. On large screens, the recipient name should be to the left and the api to the right on each list item.
- [x] Text on partial failure: Currently, the user is given an error message only when all delegations fail. However, when some fail and some do not, this message should still be provided to the user.

### Additional Information

![image](https://user-images.githubusercontent.com/103100644/231405017-9e80cae7-e754-44b1-8d10-7dbab02c8846.png)
![image](https://user-images.githubusercontent.com/103100644/231405181-59155787-2c0e-4084-9fc7-68497f02f40b.png)
![image](https://user-images.githubusercontent.com/103100644/231405448-0433044f-89e8-4fe6-9350-0b78b837cce4.png)

**Comment by Randiabs** [comment]
Sjekket, ok
