### ISSUE TITLE
API delegering - Maskinporten link doesnt open in a new tab

### ISSUE THREAD

**Issue by anishastphen** [Altinn/altinn-access-management-frontend#286]
Open delegaions overview page
Click on link to Maskinporten - this opens in same tab

In the API delegering panel, these links opens in a new tab.
Perhaps it should be the same here as well

![Image](https://user-images.githubusercontent.com/117180726/233048991-085590dc-878b-45f6-91b2-59e1fef797e2.png)

**Comment by Albertlarsen** [comment]
Yeah it's a one liner, I'll add it the PR fixing refresh token url

**Comment by Albertlarsen** [comment]
@anishastphen Deployed this some minutes ago, I put this back to test 😊

**Comment by anishastphen** [comment]
testet OK
