### ISSUE TITLE
Resources shown in Bokmål when English is selected

### ISSUE THREAD

**Issue by lovoll** [Altinn/altinn-access-management-frontend#303]
The Resources "digdir-maskinportenschemaid-671" and "digdir-maskinportenschemaid-670" is shown in Bokmål when English language is selected even when the resource is defined in English.

"title": {
		"en": "Altinn Service Owner API: App Instances (full access)",
		"nb": "Altinn tjenesteeier-API: Appinstanser (full tilgang)",
		"nn": "Altinn tenesteeigar-API: Appinstanser (full tilgang)"
	}

"title": {
		"en": "Altinn Service Owner API: App Instances (read-only)",
		"nb": "Altinn tjenesteeier-API: Appinstanser (lesetilgang)",
		"nn": "Altinn tenesteeigar-API: Appinstanser (lesetilgang)"
	}

When trying to delegate when site is set to English this is still shown in bokmål

![image](https://user-images.githubusercontent.com/56019927/233311528-deaca68d-1088-407c-aaf5-71a10ceaf27a.png)

This also seems to be for the Service owner selector:

"hasCompetentAuthority": {
		"name": {
			"en": "Norwegian Digitalisation Agency",
			"nb": "Digitaliseringsdirektoratet",
			"nn": "Digitaliseringsdirektoratet"
		},
		"orgcode": "DIGDIR",
		"organization": "991825827"
	}

**Comment by anishastphen** [comment]
testet OK
