### ISSUE TITLE
API delegering - scroll bar in delegations overview page when it has more content

### ISSUE THREAD

**Issue by anishastphen** [Altinn/altinn-access-management-frontend#312]
User should have done API delegations to multiple orgs for several APIs
Go to delegations overview page and expand the APIs
Drag down the scroll bar corresponding to the delegations.
You can see that scroll bar reaches the bottom, and yet we haven't reached the bottom of the content.
And when you scroll through the page down, you get to see the scroll bar again

![Image](https://user-images.githubusercontent.com/117180726/233351904-be8b1998-0d04-4d8e-8308-e0431441ae2e.gif)

**Comment by Albertlarsen** [comment]
Denne er klar for design review forresten 😄 @Randiabs @hannekristin

**Comment by hannekristin** [comment]
@Albertlarsen Det skal jeg se på. Hvilket miljø?

**Comment by hannekristin** [comment]
Testet ok

**Comment by anishastphen** [comment]
testet OK
