### ISSUE TITLE
BFF endepunkt for å søke etter lenketjenester | Lenketjenester

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#349]
### Description

Notat: Endepunktet som gjør søket her kan få 1600 resultater så da må dette kallet skje i BFF.

<img width="621" alt="image" src="https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/e73237be-28db-490e-b2c8-531d28428f8b">

**Comment by allinox** [comment]
More detailed specification of this issue in #393 
Closing this as duplicate
