### ISSUE TITLE
Focus state on ActionBar looks kinda buggy

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#364]
### Description of the bug

This doesn't actually break any accessibility rules, but it looks kinda weird. It should at least show all the sides of the border and probably also encompass the arrow-down icon to the left. Whether it should outline the entire bar (including the actions) is a question that should probably be discussed with UX.

We should also look into unifying the look of all our focus states so that they look and act similarly to that of the Design system which has recently changed theirs into a black and yellow outline.

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/62b4cab9-f0a3-4362-bceb-bc27c5af85b4)

### Steps To Reproduce

1. go to Overvew page
2. use tab to focus on an ActionBar

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/67594a56-9ef3-4972-8c60-eab2491032f2)

**Comment by Randiabs** [comment]
Sjekket, syns det ser bra ut nå som også nedover pilen er med i fokuset.   Er dette knapp og fokus fra design systemet @allinox og @Albertlarsen  ?

**Comment by Albertlarsen** [comment]
@Randiabs Det er basert på fokus fra design systemet ja
