### ISSUE TITLE
Non-expandable ActionBar should not have focus

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#366]
### Description of the bug

When an ActionBar is not expandable and has no onClick function it should not be focusable as a button.
The actions, however, should be (as they are today).

### Steps To Reproduce

1. Go to Choose Org page
2. Use tab to navigate the page
3. Observe that the ActionBar gets focus even if it is unclickable

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/8e5f3db1-0a4b-4420-8f2a-be1d2a58498a)

**Comment by Randiabs** [comment]
Sjekket, ser ok ut. Satt til test
