### ISSUE TITLE
Add aria-label text on all SVGs in code base

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#376]
### Description

Description:
As part of improving accessibility in our code base, we need to ensure that all SVGs used throughout the application have appropriate alt-text. Alt-text provides a textual description of the content of an image for users who may have difficulty seeing or cannot see the image.

Currently, some SVGs in the code base do not have alt-text specified, which can hinder users with visual impairments from understanding the content conveyed by these images. To address this issue, we should add alt-text to all SVGs to ensure a more inclusive and accessible user experience.

Tasks:

Review all SVG files in the code base.
Identify SVGs that are missing alt-text.
Add descriptive alt-text to each SVG, providing a clear and concise description of the image content.
Update the code references to include the alt attribute with the corresponding alt-text.
Expected Outcome:
By adding alt-text to all SVGs, we will improve the accessibility of our application, making it more inclusive and user-friendly for individuals with visual impairments. This enhancement aligns with our commitment to accessibility best practices and ensures compliance with accessibility standards.

Note: It's important to consider the context and content of each SVG when writing alt-text to accurately convey the meaning or purpose of the image.

**Comment by allinox** [comment]
@Albertlarsen 

Ref comment on PR 399 - are you working on this right now?

**Comment by Albertlarsen** [comment]
@allinox nope, I'm not working on anything that isn't in 'in progress'

**Comment by allinox** [comment]
@Albertlarsen 

Ok, I was just wondering since you commented about the topic on another PR a couple of days ago 👍

**Comment by Albertlarsen** [comment]
@allinox 
this task is perhaps not that relevant after our discussion. Also it seems like alt-texts is not needed on icons that's just for illustrations.

**Comment by allinox** [comment]
@Albertlarsen 
True, if the goal is accessibility, we're already covered with aria-labels in that regard, so the only thing it would help for are the cases with the add and delete buttons if the user has poor connection so the image isn't loaded. But I don't know how far we should stretch ourselves to cater to cases like that.
