### ISSUE TITLE
Focus and open state remains even after element is selected

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#377]
### Description of the bug

This is likely due to the index of a map-function is used as the keys on the list of elements, which is not ideal.
Indexes should be unique.

### Steps To Reproduce

1. Go to Choose API or Choose org
2. Choose the first API/Org in the list
3. The chosen element is added to theright list and removed from the left
4. Observe that the hover-state for the add-button on the next element is now active, even though this particular element was never interacted with

Note: The same is true for the open-state

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/d8036969-d6db-41cb-9084-954a5f3080a8)

**Comment by Randiabs** [comment]
Sjekket, ser bra ut.
