### ISSUE TITLE
Offered/Received Maskinporten delegations does not list relevant scopes on resources

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management-frontend#384]
### Description of the bug

![image](https://user-images.githubusercontent.com/40996230/228557609-1ddf15b0-7496-4710-8d22-558f370ee083.png)

The description of the resources in Offered and Received maskinporten delegations does not include the relevant scopes of the resource.

This is already set on the internal Delegation model in DelegationService, but it is missing in the DelegationExternal model returned by the /offered and /received API endpoints

### Steps To Reproduce

Offered:
1. Login with DAGL and go to organizations Profile page
2. Click on the "Access to the Application Programming Interface - API" panel and click "Go to delegated API accesses" button
3. If the organization does not have any active delegations a delegation must be made for any resource to any other org.
4. Expand the organization having received delegation

Received:
1. Login with DAGL and go to organizations Profile page
2. Click on the "Access to the Application Programming Interface - API" panel and click "Go to delegated API accesses" button
3. If the organization does not have any active delegations a delegation must be made for any resource to any other org.
4. Expand the organization having received delegation

Add scopes like in this picture:

![Image](https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/b1622a3f-a737-45f4-be29-1920ac1a78d9)

Design review:

- Gå til overviewet og se på ActionBarContenten hvordan vi skal vise scopes der på en oversiktlig måte

**Comment by allinox** [comment]
@jonkjetiloye 

As far as I can see, we don't receive scopes as part of the offered/received call for the overview - is this something we can get ahold of a different way?

And if so, should it be prioritized?

(Perhaps this is something that can be discussed at refinement)

**Comment by jonkjetiloye** [comment]
@allinox It just needs to be returned by the BFF, which already has this information when retrieving the service name and description. Made a PR:
https://github.com/Altinn/altinn-access-management-frontend/pull/418

**Comment by Albertlarsen** [comment]
Change to this:



![Image](https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/07adf066-944d-498e-a4f5-28d459f9e545)

**Comment by Albertlarsen** [comment]
Overview:

- Sett API-tittel som en header (h4 eller h5)
- Ha scopes som punktliste, ikke som Liste med stripla linjer

Choose-API

- Ha scopes som punktliste, ikke som Liste med stripla linjer
- Fjern Linja imellom seksjoner inne i ActionBar
- Gjør bolda tekst til headere (h4 eller h5)

**Comment by Randiabs** [comment]
sjekket, ok
