### ISSUE TITLE
Improve BFF Endpoint Error Responses

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#386]
**Description:**

Current Behavior:
Currently, the BFF endpoints return error responses in various formats and structures. This inconsistency makes it challenging for frontend developers and consumers of the API to handle errors uniformly. Additionally, the lack of a standardized Error object makes it difficult to extract relevant information from the error responses programmatically.

Expected Behavior:
To improve consistency and ease of error handling, it is essential to standardize the Error object returned by all BFF endpoints. By adopting a consistent structure and format, frontend developers can rely on a predictable error handling mechanism. The Error object should include standard properties such as message, code, status, and details (if applicable) to provide comprehensive information about the encountered error.

**Steps to Reproduce:**

- Send requests to multiple BFF endpoints.
- Observe the different formats and structures of the error responses.
- Attempt to extract and handle the error information consistently across endpoints.
 

**Proposed Solution:**
To address this issue, I suggest the following actions:
Introduce a standardized Error object that includes common properties (message, code, status, details) in all BFF endpoint error responses.
Ensure consistent formatting and structure of the Error object across all endpoints.
Document the Error object structure in the API documentation to assist frontend developers in handling errors effectively.

**Additional Information:**
Standardizing the Error object in BFF endpoint responses will greatly simplify error handling and promote consistent practices across the frontend development team. It will enable developers to extract error information programmatically and build robust error handling workflows. Additionally, documenting the standardized Error object will improve communication and collaboration between frontend and backend teams.

**Comment by sivaglen** [comment]
Denne er blokkert i påvente av at vi avklarer hvordan vi skal dele feilkode mellom backend og frontend. 
https://github.com/Altinn/altinn-access-management/issues/406

**Comment by Albertlarsen** [comment]
Closer denne inntil vi har noe håndfast å gjøre her fremover
