### ISSUE TITLE
Fix index.cshtml file to use environment specific path

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#390]
### Description

Description:
The index.cshtml file in our project currently uses a hardcoded path, which causes issues when running up the application in different environments. To ensure portability and adaptability, we need to modify the index.cshtml file to use an environment-specific path.

Expected Behavior:

The index.cshtml file should dynamically generate the path based on the current environment, allowing for seamless hmr.

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/42a47025-f30f-47df-98d3-c8977a3426c8)

**Comment by Randiabs** [comment]
Hva skal vi på UX sjekke her @Albertlarsen ?

**Comment by Albertlarsen** [comment]
@Randiabs Ingenting, den skulle egentlig blitt satt rett til Done
