### ISSUE TITLE
 BFF: Implementer API for delegering

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#396]
### Description

Denne oppgaven omhandler BFFen og implementasjon av API som skal brukes av FrontEnd.

Dette APIet må kalle et endepunkt i backend for å videresende informasjon fra frontend, ta imot respons, og sende det tilbake til frontend.

Detaljer er per nå noe uklart, men det er mulig det vil bli brukt en RightsID for hver delegeringsresurs.
Det må også lages en mock og mockdata som kan brukes inntil backend-implementasjonen er ferdig.

### Additional Information

Snakk med backend om hvordan modellen for delegering ser ut og hvordan returnerte feilmeldinger kommer til å se ut.

**Comment by Albertlarsen** [comment]
What's the differene between this and #409 @allinox?

**Comment by allinox** [comment]
@Albertlarsen 
They're kinda different sides of the same coin.
This task relates to the BFF implementation, while #409 is the front-end task where the frontend will make use of the endpoint created in this task.

**Comment by Albertlarsen** [comment]
Allright, personally I'd change the title of #409 and add a picture to make it more clear what the task is.

**Comment by allinox** [comment]
Well this task _was_ titled to more clearly point out the difference, but then you changed it 😂

**Comment by allinox** [comment]
And the same is true for #409 😅

**Comment by Albertlarsen** [comment]
![image](https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/391f4933-43d8-4613-b6bf-71e100682fec)

**Comment by Albertlarsen** [comment]
Ahh then it makes sense, think I misunderstood what the first title of the task was. I'll change the title #409 and also update the description as it is a bit outdated

**Comment by allinox** [comment]
Sounds good! 😊
