### ISSUE TITLE
Light header color for page component

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#400]
### Description

The design on Single Rights calls for a white header instead of the old blue, but this is as of now not supported by the page component

- [x] Add support of an alternative header version with white colored background and black colored content (text and icon). This variant should probably be called 'light' or something similar. 
  - [x]  While we're at it, we might as well add a red 'danger' variant as well

- [x] Change API-delegation to use this new variant on all pages so that we don't differ too much between solutions. (Obs: Check with UX and the team before making this change)

### Additional Information

[Current design](https://www.figma.com/file/ESobgAq072y7eQa4gP1JCKER/Profil?type=design&node-id=6723-92391&t=g9SPujfQRcr4jY4c-0):

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/6f9ada3f-1b50-406f-90a0-41a75950120a)

**Comment by hannekristin** [comment]
i velger å ikke bytte til hvit header. Ber om at det endres tilbake til opprinnelig farge.
