### ISSUE TITLE
Implement search-section

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#405]
### Description

As per the design, the search section will consists of three main elements: 

- [x]  One Search field component

- [x]  One Filter component with searchable seviceowner filters

- [x]  An arbitrary number of chip-components, mapped from the chosen filters gained from the filter component. When a chip is deleted by the user, the filter should be updated to reflect this change.

Implement the frontend elements in this section. The data used for the filters can be use mocked in the frontend, and no real search logic is needed for now (as this will be implemented in the BFF and connected with frontend in a different issue). But the chip-filter relationship should work as specified.

### Additional Information

[Design](https://www.figma.com/file/ESobgAq072y7eQa4gP1JCKER/Profil?type=design&node-id=6723-92391&t=g9SPujfQRcr4jY4c-0) of the main page:

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/78e4170f-befd-4b23-8622-01ce702c0853)

**Comment by allinox** [comment]
@hannekristin og @Randiabs 

Denne er klar for designreview og kan finnes i [AT23](https://am.ui.at23.altinn.cloud/accessmanagement/ui/delegate-single-rights/choose-service) 😊

En liten disclaimer bare: 
Tjenesteeierene i filteret er pr nå hardkodet og vil ikke alltid korrespondere med dataen i at23 (Kun digitaliseringsdirektoratet og Brønnøysundregistrene gjør det)
Det er også pr nå veldig dårlig datakvalitet på resursene i resursregisteret i at23. Såvidt jeg har sett er det kun én resurs som har beskrivelse og mange mangler tjenesteeier og til og med tittel. Dette problemet er imidlertid utenfor scopet til denne oppgaven.

**Comment by hannekristin** [comment]
Hvor er det egentlig vi finner dette? Finner det ikke under delegering av enkeltrettighet.

**Comment by allinox** [comment]
@hannekristin 

Dere finner den på lenken jeg sendte i forrige melding - i AT23
(Altså her: https://am.ui.at23.altinn.cloud/accessmanagement/ui/delegate-single-rights/choose-service)

**Comment by hannekristin** [comment]
Søk og filtrering ser ut til å fungere greit.
