### ISSUE TITLE
Generell feilmelding på sikkerhetsnivå for lavt

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#406]
### Description of the bug

UX har fortalt oss at denne generelle feilmeldingen under dukker opp selv om den burde vist: "Ikke høyt nok autorisasjonsnivå". Frontend trodde API-delegerings accordion i razor pages skjulte accordionen fr brukere med for lavt autorisasjonsnivå.

<img width="681" alt="image" src="https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/a8d4e996-c388-4f64-84d7-b5be70aef203">

### Steps To Reproduce

Gå til overviewet på api-delegering

**Comment by jonkjetiloye** [comment]
Refinement: sikkerhetsnivå 2 Altinn pålogging vil bli fjernet om ikke lang tid så ser det som lite behov å bruke tid på å løse dette nå
