### ISSUE TITLE
X-knapp sender deg til en persons profil og ikke bedriftens profilside

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#407]
### Description of the bug

Noen ganger når man trykker på x-knapp havner man på personens profil-side og ikke på bedriftens, er det etter en viss tid?

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/1a536f44-0411-4a3f-8687-4dd435443c7d)

### Steps To Reproduce

Gå til api-delegering, vent i en del minutter og trykk på x-knapp

**Comment by jonkjetiloye** [comment]
Refinement:
workaround kan være å alltid sette URL parameter `?R={AltinnPartyId}` i redirect tilbake igjen til A2 profil

ellers trengs det mer analyse for om man skal finne ut rot årsaken til hvorfor A2 mister avgiver kontekst

**Comment by Randiabs** [comment]
Ble det ikke sagt på refinement at denne ble ikke prioritert å rette opp i, i og med at altinn innlogging blir borte fra høsten av ?? hva skal reviewes ? @Albertlarsen

**Comment by Albertlarsen** [comment]
@Randiabs Nei det var en annen vi snakket om da. 

For å teste det her så er det bare følge det som står tydelig i issuen her 😊

> ### Steps To Reproduce

> Gå til api-delegering, vent i en del minutter og trykk på x-knapp

**Comment by Randiabs** [comment]
Fulgte oppskrift i issuen, jeg kom tilbake på virksomhetens profilside. Trengs det da noe mer review på denne ? @Albertlarsen

**Comment by Albertlarsen** [comment]
Da skal det være bra 😊
