### ISSUE TITLE
Implement navigation/give access section on the Choose Service page

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#408]
### Description

The main page has two "navigation" buttons: Cancel and Give access.
These buttons and their corresponding functionality needs to be implemented in accordance to the design

- [x] Cancel: Secondary button that takes you back to 
the A" page 'Gi og fjerne rettigheter'

- [x] Give access: Pramrary button that opens a popover with a warning text and another primary button (Confirm delegation). It is _this_ button inside the popover that actually performs the delegation. (Though implementing this is outside the scope of this task)

Design review:
1. Gå til https://am.ui.at23.altinn.cloud/accessmanagement/ui/delegate-single-rights/choose-service
2. Scroll nederst på Pagen og se på navigasjons-seksjonen

### Additional Information

[Design:](https://www.figma.com/file/ESobgAq072y7eQa4gP1JCKER/Profil?type=design&node-id=6723-92391&t=79Co7SZF69N9z27a-0)

**Comment by hannekristin** [comment]
Får ikke den lenken til å fungere @Albertlarsen

**Comment by Albertlarsen** [comment]
Woops, den her lenken skal fungere: https://am.ui.at23.altinn.cloud/accessmanagement/ui/delegate-single-rights/choose-service

**Comment by hannekristin** [comment]
Kom inn med den, men får server error på Avbryt-knappen og kommer til en tom side med Gå videre-knappen: 

![Image](https://github.com/Altinn/altinn-access-management-frontend/assets/103100644/9c947f77-3bbb-48c6-b9d8-338c762e3316)

**Comment by Albertlarsen** [comment]
Den siden der er meningen skal se sånn ut etter man trykker Videre-knappen fordi jeg holder på med oppsettet av den siden der i oppgaven jeg holder på med nå.

Avbryt-knappen skal jeg sjekke ut.

**Comment by Albertlarsen** [comment]
Er et URL parameter som ikke var satt på den tydeligvis. Fikser det når jeg får vite hva jeg skal sette.

**Comment by Randiabs** [comment]
I følge skisser og anbefaling fra designsystem skal knappene plasseres nederst på venstre side så vidt jeg vet. (om ikke endringer er kommet på dette)  men se skissene så har de også knappene nederst il venstre

**Comment by Albertlarsen** [comment]
@Randiabs allright, jeg opprettet issue #542 som vi kan fikse dette i slik at vi får flyttet alle navigeringsknappene i hele løsningen til venstre og closer denne tasken

**Comment by Albertlarsen** [comment]
Closer denne så fikser vi navigation-buttons til venstre side i tasken
