### ISSUE TITLE
Frontend: Integrate frontend with delegation endpoint in BFF

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#409]
### Description

When user clicks the confirmation button, the chosen resources should be delegated by calling the BFFs delegation-API.

The process of delegating might take a while depending on the number of chosen resources. Thus, while this is loading, ProgressModal should be displayed to the user as a sort of popover modal on top of the main page.
Make the spinner correspond to the percentage of performed delegation to give the user an indication of how far along the process is. Use ProgressModal for showing progress.

Design review:
1. Gå i at23 og til ChooseRights
2. Velg rettigheter og trykk fullfør

<img width="726" alt="image" src="https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/0d459f37-6764-4aca-8eaf-71c89265951a">

<img width="824" alt="image" src="https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/820d82b0-63c8-42d1-9124-f89f4579dd4f">

**Comment by Albertlarsen** [comment]
closer denne siden det ikke var noe kommentarer i design-møtet.
