### ISSUE TITLE
Display result of delegation on receipt

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#411]
### Description

The rights that have been delegated has to be displayed on the receipt page.

Each service should be displayed as an ActionBar, however, the desigh is not fully finished on the content of these. 
This will have to be followed up on.

### Additional Information

[Design:](https://www.figma.com/file/ESobgAq072y7eQa4gP1JCKER/Profil?type=design&node-id=6723-92391&t=79Co7SZF69N9z27a-0)

**Design review:**
- Velg Det magiske klesskapet, Brannbilen i Brønnøysund, Snarveien - Lenketjeneste og A3 app 2 til å delegere
- Gå gjennom løpet frem til kvitteringssiden
- Du skal nå kunne se eksempler på 1 feilet, 1 suksessfull og 1 delvis feilet tjeneste

**Endringer gjort undeveis i utviklingen:**
- Når delegeringer feiler så teller vi antallet som feiler for en tjeneste og legger de med flest feilede øverst. Antallet som feiler vises til høyre i ActionBaren, se bildet under
- Vi viser hvilke rettigheter som feilet der alle rettighetene feilet også slik at bruker har kontroll på hvilke som feilet med tanke på at brukeren kan ha glemt hvilke rettigheter han glemte å delegere på forrige side.

![Image](https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/98e910a1-b540-4c85-9d19-0ed0f0d77b99)

**Comment by hannekristin** [comment]
![Image](https://github.com/Altinn/altinn-access-management-frontend/assets/103100644/bf0e0b41-b911-40d4-a622-7fe75bbb9382)

**Comment by Randiabs** [comment]
Har vi en lenke til der vi kan teste dette ? :-)

**Comment by Albertlarsen** [comment]
https://at22.altinn.cloud/ui/authentication

**Comment by Randiabs** [comment]
Har vi en annen lenke som fører til der vi kan teste dette ? og ikke til innlogging som den overfor fører til  :-)

**Comment by Albertlarsen** [comment]
https://am.ui.at23.altinn.cloud/accessmanagement/ui/delegate-single-rights/choose-service

**Comment by Albertlarsen** [comment]
Man må logge inn uansett da tror jeg

**Comment by hannekristin** [comment]
Teksten øverst på kvitteringssiden skal være: Du gir disse rettighetene til FORNAVN ETTERNAVN


![Image](https://github.com/Altinn/altinn-access-management-frontend/assets/103100644/41072156-ddc5-4850-be94-47b77d36c2e0)

**Comment by allinox** [comment]
Hei, beklager å butte inn i denne tasken, men jeg prøver å rydde opp litt i backloggen og jeg ser at denne tasken har ligget urørt en stund

@hannekristin 
Jeg kan gjøre en klapp endring på teksten så vi får lukket tasken, men jeg skjønner ikke helt hva det er teksten skal endres til? 😅

Pr nå ser det slik ut:
![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/f3b0947c-1d58-400f-b1e4-d0e5136bcc1f)

Altså sier teksten at "FORNAVN ETTERNAVN har fått disse tilgangene" som jeg trodde var meningen siden vi er på kvitteringssiden og delegeringene allerede er gitt (og som jeg tror stemmer overens med figma-designet også:)

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/aca850f7-795d-40ee-9a9d-42cf9ffddaea)

Kan du si litt nøyere om hva det er som må endres på her så jeg kan slenge det inn i en PR?

**Comment by hannekristin** [comment]
@allinox Beklager. Jeg så ikke at denne saken kun gjaldt kviteringssiden. Det er oppsummeringssiden før kvitteringssiden som er feil. Lukker denne saken.

**Comment by allinox** [comment]
@hannekristin 
Den er grei - takk for kjapt svar! 😄
