### ISSUE TITLE
Navigation section on the receipt page

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#413]
### Description

This page has two buttons, one for exiting the process and one for starting a new delegation process.

### Additional Information

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/8e052714-84ef-41a6-98f1-b331fad294d0)

**Comment by Randiabs** [comment]
Prøver i test å komme i flyten til denne siden, men det får jeg ikke til. Stopper opp før denne siden kommer.  Hvor skal dette kunne testes ? @Albertlarsen

**Comment by Randiabs** [comment]
Er denne laget ferdig ??  @Albertlarsen  Når æ tester flyten og kommer til siste side, ser det ikke slik ut som på skissen over. Se bilde under.



![Image](https://github.com/Altinn/altinn-access-management-frontend/assets/94835837/f58224eb-dab4-4ee2-a0f1-2f4dcbf007d6)

**Comment by Albertlarsen** [comment]
Ja til nå ser det sånn ut, oppgaven går jo ut på å lage "Gå-til-delegeringsside"-knappen

**Comment by Albertlarsen** [comment]
I henhold til møtet legger jeg til en knapp til "ferdig" som ikke har funksjonalitet enda.
