### ISSUE TITLE
Create responsive design for S5a | ApiDelegationConfirmationPage

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#44]
This task consists of making component the page on http://local.altinn.cloud/accessmanagement/ui/api-delegations/confirmation responsive. An example on how it can be made mobile friendly can be seen in picture below, but don't follow that example blindly as there most likely will be some errors in the sketch that I haven't spotted yet. Use margins, spacing, etc like you feel makes sense. 

**Additional info:**
We follow the design system's px-definitions on screen sizes: 
- phone view: 280-768 px.
- pc view: 769px and up

**AC:**
- Page: am.ui.at23.altinn.cloud/accessmanagement/ui/offered-api-delegations/confirmation  looks nice on all screen sizes.

Figma link here: https://www.figma.com/file/ESobgAq072y7eQa4gP1JCKER/Profil?node-id=6550%3A84073&t=eAUiGxV6m3Jd5u5b-0

Figma link here: https://www.figma.com/file/ESobgAq072y7eQa4gP1JCKER/Profil?node-id=6550%3A85281&t=eAUiGxV6m3Jd5u5b-0

![Image](https://user-images.githubusercontent.com/31471142/212767877-614cd4b1-aa66-44eb-b71d-1f4f6d4f726c.png)

**Comment by hannekristin** [comment]
På mobil bør navn på etat og organisasjonsnummer legges på linjen under. Det ser greit ut på iPad mini. 


![Image](https://user-images.githubusercontent.com/103100644/228511288-18fdcc16-0447-435b-bfdf-93448a9874c1.png)


![Image](https://user-images.githubusercontent.com/103100644/228511196-70e96edf-02f9-42b2-b3ff-78cf8ce0f272.png)

**Comment by Randiabs** [comment]
Det ser greit ut i forhold til at etats navnet havner på linjen under. Men har dere fjernet at organisasjonsnummeret for virksomheten som mottar api vises ?  @Albertlarsen

**Comment by hannekristin** [comment]
Org.nr vises heller ikke på større enheter. det gjorde det før siste endring


![Image](https://user-images.githubusercontent.com/103100644/234222259-2865c84b-c475-4733-afcb-302b7a7c6c16.png)

**Comment by Albertlarsen** [comment]
@hannekristin Åja, det skal jeg fikse asap 😊

**Comment by Albertlarsen** [comment]
Jeg kan legge det til men da blir det sånn her på små skjermer:
<img width="606" alt="image" src="https://user-images.githubusercontent.com/31471142/234231631-86219200-8c42-46ba-bf76-88291c824d24.png">

**Comment by hannekristin** [comment]
Det ser bra ut :-)

**Comment by Randiabs** [comment]
sjekket, ser bra ut. satt til test
