### ISSUE TITLE
Create responsive design for S5b | ApiDelegationReceiptPage

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#45]
This task consists of making component ConfirmationPage for receipt responsive. An example on how it can be made responsive for smartphones can be seen in picture below, but don't follow that example blindly as there most likely will be some errors in the sketch that I haven't spotted yet. Use margins, spacing, etc like you feel makes sense. 

**Additional info:**
We follow the design system's px-definitions on screen sizes: 
- phone view: 280-768 px.
- pc view: 769 px and up

**AC:**
- Page: am.ui.at23.altinn.cloud/accessmanagement/ui/offered-api-delegations/receipt  looks nice on all screen sizes.

Figma link here: https://www.figma.com/file/ESobgAq072y7eQa4gP1JCKER/Profil?node-id=6550%3A84073&t=eAUiGxV6m3Jd5u5b-0

![Image](https://user-images.githubusercontent.com/31471142/212766765-88c9065f-dfaa-4a9f-a6d4-8d72cafa88cb.png)

**Comment by Randiabs** [comment]
sjekket ulike views, ser ok ut. Satt til test

**Comment by hannekristin** [comment]
Satte denne tilbake. Samme som #44 Forslag her: 

![Image](https://user-images.githubusercontent.com/103100644/228819952-96475f69-0877-4b1f-8db6-68ce8f3d9814.png)

**Comment by Randiabs** [comment]
Sjekket, ok. Satt til test
