### ISSUE TITLE
set up pipeline to run Altinn3 tests

### ISSUE THREAD

**Issue by anishastphen** [Altinn/altinn-access-management-frontend#454]
set up a separate pipeline to run Altinn3 profile tests alone.
This has to be a different pipeline from Altinn2 tests as Altinn2 cypress tests are not followed up.

- [x] set pipeline to run ALtinn3 tests
- [x] publish test results after run in pipeline
- [x] set pipeline so that it runs in all environments
- [x] schedule daily runs

**Comment by anishastphen** [comment]
@rtafj

**Comment by anishastphen** [comment]
pipeline ligger her - https://dev.azure.com/digdir/Altinn/_release?_a=releases&view=mine&definitionId=61

**Comment by ivartryti** [comment]
Looks good!
