### ISSUE TITLE
Make ActionBar react with status color to BFF-response

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#457]
### Description

We have some different responses the bff can give to frontend. See json files for the different responses in folder: AccessManagement.UI.Mocks/Data/SingleRight/DelegationAccessCheckResponse

Based on the different responses the ActionBars should either be changed to the colors: Green or Red. 

This task is about making the ActionBars react to those responses.

Tasks:

- [ ] Continue developing ResourceActionBar component (that's already started developing on)

### Additional Information

Red:
If the response says the user doesn't have the access to delegate anything of the responses

Green: 
If the response says the user can delegate anything on the service.

Green with text: "Har allerede tilgang": DENNE UTGÅR
Etter melding fraI Jon Kjetil om for mye kompleksitet så utgår denne.

Design review:
1. Gå til AT23: https://at23.altinn.cloud/ui/authentication
2. Se om alt går som forventet når dere legger til og fjerner alle tjenester

<img width="806" alt="image" src="https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/37312899-d953-4c42-9812-f6b975b27e43">

**Comment by Randiabs** [comment]
@Albertlarsen   Green with text: "Har allerede tilgang": DENNE UTGÅR
Etter melding fraI Jon Kjetil om for mye kompleksitet så utgår denne.  

 Hva menes her ? Hvordan blir den seende ut ?

**Comment by Randiabs** [comment]
Får man ikke denne responsen i det hele tatt ? Ikke senere i prosessen heller ?

**Comment by Albertlarsen** [comment]
@Randiabs Nei men det er @jonkjetiloye som har detaljene på det her

**Comment by jonkjetiloye** [comment]
> Får man ikke denne responsen i det hele tatt ? Ikke senere i prosessen heller ?

Nei, ikke med mindre frontend selv gjør oppslag for å sjekke dette.

På backend API-nivå så ble det tatt en avgjørelse om å forenkle så det behandles bare som en ny delegering selv om brukeren har deler eller hele tjenesten fra før av. Så ingenting vil feile.

**Comment by Randiabs** [comment]
ok, men så lenge den blir grønn og lagt til sammen med de andre så er det jo ok i grunn.
