### ISSUE TITLE
Ny variant av ActionBar-komponent

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#468]
### Description

Vi trenger en ny variant av ActionBar som skal brukes på samme måte som en handlevogn blir brukt i en nettbutikk. Vi trenger 3 varianter:
- Success
- Danger
- Neutral(Vi har ikke skisser på denne enda men den har samme farge som Neutral stil på ActionBar).

Skissene er ikke perfekte men når det kommer til borders og alt dette så bare følg det samme som er brukt i ActionBar.

Man må vurdere ut fra kodekompleksistet om man skal lage dette som egen komponent eller om man skal legge til variant på eksisterende ActionBar. 

<img width="426" alt="image" src="https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/2a904480-97bb-4de6-8607-9180882aa32d">

**Comment by allinox** [comment]
@hannekristin @Randiabs 
Har lagt inn fiks på det vi snakket om på møtet - det vil være ute i AT om noen minutter 😊

**Comment by Randiabs** [comment]
Noterer her de sakene vi snakket om på møtet som skulle endres:
Corner radius på Actionbar settes ned til 4px.
Border rundt  innhold i "oppsamlingsboks" , er denne vanskelig å se.

**Comment by Randiabs** [comment]
@allinox  Kan du sette border rundt innhold i "oppsamlingsboks"  til
Slik: cemantic /boder/ sucsess /default 
Den skal være 1px

**Comment by hannekristin** [comment]
@allinox Kan du endre teksten og ikonet på knappen når man legger til en tjeneste til Angre istedenfor Fjern? Slik som på skissene:

![Image](https://github.com/Altinn/altinn-access-management-frontend/assets/103100644/1998e5f4-cb91-41f8-8100-ca822606233e)


![Image](https://github.com/Altinn/altinn-access-management-frontend/assets/103100644/8915349a-96d6-4f83-8d48-24969f355ee6)

**Comment by hannekristin** [comment]
Tenker vi bruker tilbakepilen når man velger, og minus når de er lagt til i oppsamlingsboksen 
![image](https://github.com/Altinn/altinn-access-management-frontend/assets/103100644/928ab7e2-7a55-46bf-963d-b53b13383213)

**Comment by allinox** [comment]
@Randiabs 

Angående border, kan jeg foreslå å bruke en litt lysere grønnfarge så den blir litt mindre skjærende?


Denne f.eks, som er ca lik i mørkhetsgrad som den vi har på grå variant uansett:
![Image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/e6eb1074-9f2b-443b-923b-8d7a463eb61a)

Istedenfor den som er default border:
![Image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/a24ac367-ebcf-4d35-a2bb-7504782fc347)

**Comment by Randiabs** [comment]
Har du @allinox sjekket med designsystemet ang spacing på chip, når man filtrerer på etat med langt navn i mobilview ? 



![Image](https://github.com/Altinn/altinn-access-management-frontend/assets/94835837/34509fac-097c-4efa-8f1f-2981a3ea7008)

**Comment by Randiabs** [comment]
Var ikke denne chipen ordnet ? altså i forhold til spacing , @allinox

**Comment by allinox** [comment]
@Randiabs 
Jo, men bugfixen ble releasa først i går og vi har ikke fått oppdatert til den versjonen av designsystemet enda, så det vil ikke synes ute i AT helt enda. Men jeg kan legge inn oppdatering i min nåværende PR så kommer det inn snart.
Har testet lokalt, og med fixen vil det se slik ut:

![Image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/3215e736-6309-4ea4-ab21-c56fd1fee0ae)

**Comment by Randiabs** [comment]
Flott, ser bra ut det. Da kan vell denne lukkes ? eller skal vi vente til endringen kommer i AT ? @allinox

**Comment by allinox** [comment]
@Randiabs 
Tenker denne kan lukkes 😊
