### ISSUE TITLE
Get receiver info based on UUID given in url

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#512]
### Description

A2 now adds UUID to url when sending user to SingleRights in A3. This can be used to get party information of the person/org to delegate to, using the new endpoint [(partylistbyuuid) in the Registry](https://github.com/Altinn/altinn-register/commit/3f69df17bd8b80b864250aa6f6339d0abc8026bb).

Url will contain either partyUUID or both partyUUID and userUUID.
Frontend needs to read the id(s) from url and perform a lookup to get party information to be stored in the redux state.

Cases:
- url has userUUID and partyUUID: Delegating to a person -> use userUUID for lookup and store as person
- url has only partyUUID: Delegating to an org -> use partyUUID for lookup and store as org
- url has neither and nothing is stored in state: Something is wrong -> display error

### To Do: 

- [x] BFF:
  - [x] Add new endpoint  GetPartyByUUID to LookupController that passes on result from Register lookup
    - [x] Endpoint calls Register in RegisterClient
    - [x] Mock endpoint in RegisterClientMock
    - [x] Add integration tests to new endpoint
  - [x] Add new endpoint  GetUserByUUID to LookupController that passes on result from Profile lookup
    - [x] Endpoint calls UserProfile in ProfileClient
    - [x] Mock endpoint in ProfileClientMock
    - [x] Add integration tests to new endpoint

- [x] Frontend:
  - [x] Get rceiver's uuid from url
  - [x] Get party-info from new Lookup endpoint in BFF. Use rtk Slice or Query? -> Query
  - [x] Store the uuid to the url on all pages for more reliable storage
  - [x] Replace all texts saying ANNEMA FIGMA with actual receiver name.
    - [x] Case 1: UserType = 1 Means recipient is a person -> Use users full name
    - [x] Case 2: UserType = 2 Means it's a self-registered user, which cannot be delegated to ->  display Alert with error message
    - [x] Case 3: UserType = 3 Means it's an organization-user -> Use a combination of user name and connected party name (name of connected organization)
    - [x] Case 4: Party is an Org -> Use org name and number
    - [x] -> make a reusable function for getting recipients name and type that can be used on all pages
  - [x] Delegate to recipient's uuid

### Additional Information

Name of reciptient is to be used in the solution

<img width="470" alt="image" src="https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/02ff55bd-11ad-4713-8b6f-ca8c6c5c0acb">

**Comment by allinox** [comment]
Merging of this task is BLOCKED by [#596](https://github.com/Altinn/altinn-access-management/issues/596)

**Comment by hannekristin** [comment]
Testet ok. Hvis man derimot avbryter med krysset kommer man til profilsiden
