### ISSUE TITLE
Be om Tilganger - ChooseService side

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#534]
### Description

Flyten 'Be om tilganger' er på mange måter en speiling av flyten 'Deleger tilganger'.

Spesielt på siden 'Velg tjeneste' så kan nok en hel del av frontend kode gjenbrukes, spørsmålet er bare hvor mye.

- [x] Finn ut av hva som kan gjenbrukes - dvs, som kan flyttes til gjennbrukbare komponenter til bruk i begge flyter - og hva som bør bør være egetskrevet for hver side.
- [x] Lag den nye siden request-single-right/choose-service og implementer denne etter planen funnet over
- [x] Gjør nødvendige endringer på delegate-single-rights/choose-service

### Additional Information

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/30ff2c13-fe69-436c-b33a-00d32c363217)

**Comment by allinox** [comment]
@Randiabs @hannekristin 
For å komme til denne siden så kan dere gå inn på denne lenken: https://am.ui.at23.altinn.cloud/accessmanagement/ui/request-single-rights/choose-service 😊

**Comment by hannekristin** [comment]
Knappene skal være omvendt. Se skissen øverst

![Image](https://github.com/Altinn/altinn-access-management-frontend/assets/103100644/2512a29a-18cb-4478-b75b-949dfee45e5b)

**Comment by allinox** [comment]
@hannekristin Tenker det går under knappe-oppgaven til Albert, så vi ikke roter med det samme samtidig
