### ISSUE TITLE
Move all navigation buttons to the left

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#542]
### Description

We have many views that has navigation buttons on the bottom right side of the screen. We have to move them to the left side of the screen like in the picture to make sure people with bad eye sight see them.

Also do this:
I henhold til møtet legger jeg til en knapp til "ferdig" som ikke har funksjonalitet på receipt-siden.

Design review:

- Sjekk at alle navigerings-knappene er flyttet til venstre på alle sider

<img width="1081" alt="image" src="https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/e4cc2c96-75e8-4793-a036-729f4d586452">

**Comment by Randiabs** [comment]
Knappene skal være motsatt, Neste (hovedknapp) skal være lengst til venstre.



![Image](https://github.com/Altinn/altinn-access-management-frontend/assets/94835837/6ccf292a-2b59-4733-ac0a-caabfefc4b2a)

**Comment by Albertlarsen** [comment]
@Randiabs Dette skal være fikset nå

**Comment by Albertlarsen** [comment]
Hva mener du @hannekristin? Er du i AT23? 😊

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/6a06a87d-d529-490f-80cd-8ef7a936eaaa)

**Comment by hannekristin** [comment]
Nei var på API delegering i Prod. Trodde det var endret der også. AT 23 er good :-)

**Comment by Albertlarsen** [comment]
Prod har ikke vi noe styring på når det deployes til så ingen av endringene som er her i Design Review kommer der før etter dere har closet issuene
