### ISSUE TITLE
Make ChooseRightsPage get urn from ServiceRegistry

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#545]
### Description

Currently there's only a hard coded value for setting the To-field in DelegationRequestDto. This task is about fixing that 

Tasks:
- [ ] Update the field 'urn:altinn:resource' in DelegationRequestDto to be set from the resourceReference field in the data from resource registry.

**Comment by allinox** [comment]
Fixed together with issue #434
