### ISSUE TITLE
UserInfoBar does not support users representing themselves

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#568]
### Description of the bug

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/52b7ab7b-ad65-4732-8fee-6a64f250876b)

When a user represents themselves the UserInfoBar in the top right corner currently displays their name twice which looks kinda weird. When a user is not representing someone else their name should only be displayed once and the 'for' should not be there.

It should look something like this:
![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/28f72ebf-2a8f-4f7c-b7ab-6b789f781612)

### Steps To Reproduce

1. Go to https://am.ui.at23.altinn.cloud/accessmanagement/ui/request-single-rights/choose-service
2. Log in as a private person not representing any orgs
3. Observe the user info bar in the top right corner

**Comment by Randiabs** [comment]
Sjekket, ok. Lukker saken
