### ISSUE TITLE
Melding når brukeren forsøker å delegere API til eget org.nr.

### ISSUE THREAD

**Issue by hannekristin** [Altinn/altinn-access-management-frontend#570]
Dersom brukeren forsøker å delegere et API til den virksomheten som er valgt, blir ikke avgiveren valgt, og brukeren får opp en Alert med en beskjed.

Design review:

- Endret til tekst: Det er ikke mulig å delegere API til deg selv. Skriv inn et annet organisasjonsnummer for å fortsette.

![Image](https://github.com/Altinn/altinn-access-management/assets/103100644/84a6b444-f4f7-442a-8db5-840ea01014d5)

**Comment by Randiabs** [comment]
Tenker at vi fjerner den første setningen under overskrift i alert. Da den setningen er misvisende. Se bilde under:



![Image](https://github.com/Altinn/altinn-access-management-frontend/assets/94835837/33865206-78aa-4826-b2f8-3947124d063b)

**Comment by hannekristin** [comment]
Testet ok

**Comment by hannekristin** [comment]
Lukkes
