### ISSUE TITLE
Change deprecated ref from nuget to framework in class lib

### ISSUE THREAD

**Issue by simen-rekkedal** [Altinn/altinn-access-management-frontend#589]
### Description

Change from nuget package to framework reference for deprecated package in class library.

### Additional Information

See these articles: 
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-6.0&tabs=visual-studio 
https://stackoverflow.com/questions/75147859/net-7-dependencies-and-nuget-packages-managing 

Altinn\altinn-access-management-frontend\backend\src\Altinn.AccessManagement.UI\Altinn.AccessManagement.UI.Core\Altinn.AccessManagement.UI.Core.csproj

Add the following to the Altinn.AccessManagement.UI.Core.csproj file:

 <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

### Tasks

1. Remove nuget package
2. Add framework reference to proj file

### Acceptance Criterias

No longer deprecated nuget package warning. Same functionality retained.

**Comment by simen-rekkedal** [comment]
@acn-dgopa  mente vi burde opprette en issue slik at vi ikke glemmer dette. Vi fant denne i authentication frontenden også. Fungerer fint med framework ref istedet for nuget.

**Comment by allinox** [comment]
Assumed no longer relevant after moving to .NET 8
