### ISSUE TITLE
Take roles from backend error response and append to user error feedback

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#597]
### Description

Currently the roles that fails is just hard coded. This task is about getting the actual roles that fails from backend and display it in Alert below.

Blocked by:
- Backend not returning roles that fails

<img width="990" alt="image" src="https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/c4f51145-eae7-43b0-ad95-af67c96e4943">

**Additional info**
Backend response should return role here:
<img width="691" alt="image" src="https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/6a0d8f45-c947-470d-8a62-7b8a52fef29f">

**Comment by allinox** [comment]
This issue is invalidated as we no longer plan to display the missing roles
