### ISSUE TITLE
Alert doesn't display the right error message for non-delegable rights

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#599]
### Description of the bug

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/b33c1ac6-e857-4a86-92dc-0e9af75167f1)

The underlined message should display the reason why the user can't delegate certain rights, but right now, this doesn't seem to be the case here.

Figure out why the alert text soes not correspond to the error codes and fix this.

Current possible values of the error codes are:
![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/e06e81e4-4f03-44f2-80c1-ada60ac2c5b4)

### Steps To Reproduce

1. Go to AT22 Single rights delegation (https://am.ui.at22.altinn.cloud/accessmanagement/ui/delegate-single-rights/choose-service)
2. Choose the resource Generisk Tilgangsresurs
3. Go to the next page
4. Observe that the alert text for this resource claims that this error is new and unexpected. (Which should not be the case)

**Comment by Randiabs** [comment]
Testet ok at ikke uventet feil kommer opp i alert. Men teksten som står inne i alerten er feil likevel.
Det burde stå: 
Du får ikke delegert hele tjenesten
En eller flere av rettighetene på denne tjenesten blir ikke delegert fordi du mangler disse selv.

Daglig leder eller hovedadministrator kan hjelpe deg med dette.


Når årsaken er at tjenesteeier har bestemt at tjenesten ikke kan delegeres må det stå følgende:
Du får ikke delegert hele tjenesten
En eller flere av rettighetene på denne tjenesten blir ikke delegert fordi "navn på tjenesteeier" har oppgitt at disse kan delegeres videre til andre.




![Image](https://github.com/Altinn/altinn-access-management-frontend/assets/94835837/9436ed4c-bfb3-4807-94d1-4057879fccf8)

**Comment by Albertlarsen** [comment]
> Du får ikke delegert hele tjenesten
En eller flere av rettighetene på denne tjenesten blir ikke delegert fordi du mangler disse selv.

@Randiabs Vi får på øret fra backend at det kan være pga. Manglende roller og rettigheter at man ikke får delegert.

Kan vi endre teksten til? "En eller flere av rettighetene på denne tjenesten blir ikke delegert fordi du mangler roller eller rettigheter."

**Comment by Randiabs** [comment]
Ordet rolle kommer til å bli borte når Fullmakstgrupper kommer.  Den setningen jeg skrev er kort og konsis, syns vi skal gå for den.
Som du ser i teksten æ skrev så er det lagt inn tekst på to ulike scenarioer.

**Comment by Albertlarsen** [comment]
@Randiabs Dette skal være fikset nå

**Comment by hannekristin** [comment]
ok
