### ISSUE TITLE
Handle HTTP error responses to DelegationCheck in frontend

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#601]
### Description

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/bcd372dd-3b05-42c9-955b-2da154fd33b8)

Right now, we only handle successful responses from the call to DelegationCheck of a resource, but there will be times where such a call fails due to weak network or internal server errors and so on, currently resulting in an eternal spinner in the UI.

When f.ex. a 500 error occurs (such as in the picture), it doesn't necessarily mean that the user cannot delegate the service, thus we cannot simply mark the service red and say it's unavailable as we de with true undelegable service. We need to offer the user a chance to try again

Designs on exactly how this should look (should the service still be red? Stay gray? Turn yellow?), but the current suggestion is that An alert is displayed in the actionBar's content, saying that something went wrong (based on the HTTP error), that the user is welcome to try again and that should it continue to malfunction, they are asked to contact the service desk. In addittion to this, the 'Add' button should now say 'Try again', and still trigger the same functionality (i.e. the call to the DelegationCheck and subsequent handling of the return value).

**Comment by allinox** [comment]
@hannekristin 
Teksten er endret nå og ligger klart ute i AT-miljøene.
Men jeg innser at siden jeg nå har slått av mocken så er dette tilfellet ikke så lett å trigge lenger 😅
Så jeg legger ved et screenshot av teksten slik den ser ut nå om den blir trigget


![Image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/5e3887df-fe6e-4c4a-8652-a00b82240caf)

**Comment by allinox** [comment]
@hannekristin 
Forresten, jeg er litt usikker på om jeg bør endre knappen sin farge til rød.
Det vil jo se bedre ut, men det gjør det kanskje mindre tydelig at det er en knapp? Spesielt siden vi allerede bruker rød tekst med trekant-ikon når du ikke kan delegere noe og da er det jo _ikke_ en knapp 😅

Hva tenker dere?

**Comment by hannekristin** [comment]
@allinox Jeg tenker kanskje den bør være blå. Rødt representerer jo fare, og det er jo ikke tilfelle her. Også er det slik som du sier, at når vi bruker rød når du ikke får gjort noe.

**Comment by allinox** [comment]
Ok, da bare lar jeg den stå sånn den er nå 😊

**Comment by Randiabs** [comment]
sjekket ok, lukker saken
