### ISSUE TITLE
Display of actions does not support mobile view

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#609]
### Description of the bug

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/2d79c0e3-49b8-448c-acfe-3decfac24e18)

The actions do not seem to stack right for small screens.
Add support for dynamic wrapping

### Steps To Reproduce

1. Go to https://am.ui.at22.altinn.cloud/accessmanagement/ui/delegate-single-rights/choose-service
2. Select the service Generisk Tilgangsresurs and move to the next page
3. Resize the view to mobile size (if not already done) and observe that the actions continue past the screen edge

**Comment by hannekristin** [comment]
Testet ok
