### ISSUE TITLE
Frontend tries to delegate services even with no rights checked

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#614]
### Description of the bug

Or, well, it doesn't actually try to delegate the rights, just the service with an empty rights-list.

This doesn't actually impact the functionality in any way, what is actually delegated is still correct, but it does cause some console errors and faulty (not to mention unnessecary) calls to backend.

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/088dc0ce-9b32-41e9-bad0-1e61d7cecd6b)

### Steps To Reproduce

1. Go to the single rights page
2. Add at least two services and move to the next page
3. Uncheck all actions on all services, leaving only a single action active on a single service and all other services with no active actions
4. Click delegate while the network window is open
5. Observe that all services result in a delegate call, and that the ones without any checked actions result in requests with empty rights lists

**Comment by Albertlarsen** [comment]
There's another bug here that I'll try to fix in this task:



![Image](https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/8652d54e-4fce-4d65-9feb-999694ca077a)
