### ISSUE TITLE
Display only one action on A3 Apps in ChoosRightsPage

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#619]
### Description

Right now, all actions are displayed for all services. But with no handling of sub-resources or process steps in the Altinn Apps, this means that we can get duplicate actions belonging to different process steps or even unknown actions.

This is the current state of things:

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/43e90efb-2519-4bf8-950d-5af318c92098)

Until we can support multiple process steps and localized labels for all actions, we will handle Apps as a special case when displaying actions.
Instead of displaying all the actions individually, we will instead display a single action called "Access" ("Tilgang" på norsk) and hide all the underlying (true) actions.

This gives the following cases:

- User can delegate all actions on the app: Display "Access" as the only action. When delegation occurs, all the underlying accesses are delegated one by one.
- User can delegate _some_ actions on the app: Display "Access" as the only action and do not inform the user that there are some things they cannot delegate (the actionBar is green and with no alert). When delegation occurs, delegate all the underlying actions except the ones that the user does not have the rights to (as usual).
- User cannot delegate _any_ actions on the app: As with other resources, the actionBar should turn red in the ChooseService page and should not proceed to the ChooseRights page.

**Comment by Albertlarsen** [comment]
Can we move this from review @allinox?

**Comment by allinox** [comment]
Sorry, I forgot 😅

**Comment by hannekristin** [comment]
@allinox Er det noe som skal sjekkes på denne saken? Er det en sak som er eldre enn #599 ?

**Comment by allinox** [comment]
@hannekristin 
Denne er nok nyere enn #599 - det denne gjør er at alle apper displayer kun én rettighet som kan delegeres selv om de teknisk sett har flere.
Det ser slik ut:

![Image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/a8057753-5e41-46ee-8e79-8507a1df9fba)

**Comment by hannekristin** [comment]
Testet ok
