### ISSUE TITLE
Use new Search component from the Design system

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#622]
### Description

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/8fa84f87-8091-42be-b426-148293d9c25d)

The Design system has created a new Search component, with better features and accessibility than the one we currently use (from the Altinn design system). We should thus switch to using this one wherever we use search

One thing we need to determine is if we should continue using a "hot reload" strategy for our search or use the new "submit" feature, that the new component facilitates.

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/6392de9d-97f3-4e04-9ae3-fe4d7048b9cb)

Different strategies may be used for different places.

## Conclusion

We will use the search field without button as we do today.
This is because fast feedback is nice for the user.

To limit the number of search calls, however, we will implement a debounce function to be used on the search field.
This way we can delay reaction to change in the search query by a few milliseconds.

### Places to change:

- API delegation:
  - Org search
  - API search
- Single rights:
  - Service search

**Comment by hannekristin** [comment]
Testet ok
