### ISSUE TITLE
API-delegering | S3 | Frontend - Integrate add-button with DelegationAccessCheck in BFF

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#634]
### Description

When clicking on + button we need to check if the person has the correct authorization level and role to delegate the api. 

Tasks for frontend:

- [x] Add needed data.
- [x] Integrate frontend with BFF for doing delegation access check
- [x] Handle isLoading
- [x] Handle HTTP-error
- [x] Make retry functionality on HTTP-error
- [x] Handle error InsufficientAuthenticationLevel 
- [x] Handle all other errors by saying they should contact admin etc.

Design Review:
Endringer:
- Tilbakemelding fra Jon Kjetil om å vente med 'Gå til innlogging'-knapp til vi er ferdig med dyplenke feature.

- Go to one of the AT-environments (Not AT23) and go through the api delegation flow

- Gjorde pluss-knapp sort i stedet for grønn slik at den også fungerer ved http-error.

![Image](https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/0f5d7b99-d937-46e1-a568-d9c57eb810da)

**Comment by allinox** [comment]
@Albertlarsen 
Should this stay in Test or can I close it?
If it has outstanding testing that needs to be performed, I think it's cleaner to creat a separate task for that and to assign it to a relevant person so this task here can be closed.

**Comment by Albertlarsen** [comment]
It can be closed
