### ISSUE TITLE
Dyplenke | API-delegering

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#637]
### Description

Som bruker vil jeg kunne klikke på en lenke som tar meg direkte til prevalgte API for delegering.

### Løsning

Denne UserStoryen løses med støtte for dyplenke - dvs en lenke som tar en bruker direkte løsningen, og som inneholder parametre som gir bruker en delvis pre-utfylt versjon av delegeringsprosessen. Her vil url-en inneholde identifikatorer til maskinportenschema-resurser som skal være forhåndsutvalgt.

Vi vil kun støtte dyplenke direkte til ChooseApi-siden.

### Teknisk flyt

Når en bruker benytter seg av av en dyplenke, kommer de inn til ChooseApi- siden, som er representert av et skeleton frem til denne flyten er ferdig. Flyten består av disse stegene, i rekkefølge:

- Rendre Skeleton av siden
- Venter på innlastning av delegerbare API fra backend
- Når APIer tilgjengelig, skal resursIDer leses fra URL og valideres. En ID er gyldig dersom den finnes i oversikten over delegerbare API. En ID som ikke eksisterer her skal forkastes
- For hver gyldig ID skal resursen forsøkes å legges til. Dette gjøres ved å trigge de samme funksjonene som ellers ville skjedd i onClick-funskjonen til resursens 'Legg til'-knapp. Logikken som trigges her skal kjøre som normalt, inkludert kall til delegationCheck for å sjekke om bruker kan delegere resursen.
- Vent på svar fra alle delegationCheck-ene
- Når alt dette er gjort så kan Skeleton fjernes og den fulle siden vises

### Spørsmål som gjenstår
- Vil man bli redirecta riktig etter innlogging?

### Issues

```[tasklist]
- [ ] https://github.com/Altinn/altinn-access-management-frontend/issues/640
- [ ] https://github.com/Altinn/altinn-access-management-frontend/issues/641
- [ ] https://github.com/Altinn/altinn-access-management-frontend/issues/639
- [ ] https://github.com/Altinn/altinn-access-management-frontend/issues/638
- [ ] https://github.com/Altinn/altinn-access-management-frontend/issues/642
```

### Acceptance Criterias

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/b40fec43-2e58-4adb-bcb7-4e14e4e0a36a)

**Comment by hannekristin** [comment]
Har vi en lenke som jeg kan bruke for å teste dette? @Albertlarsen

**Comment by Albertlarsen** [comment]
Lenken til dette er ved å gå inn på profilsiden og så videre klikke seg inn på API-delegering-siden. Lenken er markert i rødt på bildet der.

**Comment by Albertlarsen** [comment]
Det der er kvitteringsiden, du må trykke start på nytt og velge noen apier

**Comment by Albertlarsen** [comment]
Closing after talks that it's okay with @hannekristin
