### ISSUE TITLE
Dyplenke | Endre api-delegeringsflyt

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#640]
### Description

Description:
Flytt Choose org-steget til å komme etter choose api-side. Oppgaven går ut på å endre navigeringsfunksjoner i navigeringsknapper til å sende deg til motsatt flyt av det den gjør idag. 

Flow skal være slik:
1. Overview
2. ChooseApi
3. ChooseOrg

Tasks: 
Endre hvor du blir navigert på sidene:
- [x] Overview
- [x] ChooseOrg 
- [x] ChooseApi
- [x] RestartPrompters
- [x] Fjern chosen-orgs feature i ChooseApiPage.
- [x] Add RestartPrompter to chooseOrgsPage

AC:
- Alle navigeringsknapper for api-delegering tar deg til riktige sider. 

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/c61631ef-e8d4-4ea2-9f4c-30030bd84284)

**Comment by hannekristin** [comment]
Hvilket miljø kan vi teste dette i?

**Comment by allinox** [comment]
@hannekristin 
Dette kan testes i alle AT-miljøer

**Comment by hannekristin** [comment]
Testet ok
