### ISSUE TITLE
Dyplenke | Lag skeleton for ChooseApi

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#642]
Lag en skeleton-side for ChooseApi og få den til å vises når man kommer til siden med en link med flere ressurser i linken. 

Additional info:
Skeleton forutsier strukturen på siden før den er lastet og har fått respons på Delegationcheck.

Skeleton er nå tilgjengelig i Designsystemet: https://github.com/digdir/designsystem/issues/1101

Illustrasjon av skeleton
![image](https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/3224e954-87b9-4504-aaf1-d488a34d46e1)

**Comment by Albertlarsen** [comment]
@allinox Jeg ser for meg dette vil være litt vanskelig å legge til for vi vil trenge noe funksjonalitet som ser om brukeren kommer fra en dyplenke eller om de har startet prosessen fra start for skeleton skal jo kun vises når de kommer fra en dyplenke. Evt. Kan man legge til en redux-state som kan brukes til å si fra om at brukeren ikke kommer med direktelenke?

**Comment by allinox** [comment]
@Albertlarsen 
Jeg tekte egentlig at skeleton bør være der uansett om man kommer fra dypleneke eller ikke jeg, men at den forsvinner veldig fort hvis det ikke er noen id-er i url-en og prosessen med å legge dem til går veldig fort. Det er jo her prosessen med å legge til nye API starter så det at det starter med en skeleton mens vi venter på å inn få bl.a. APIene fra backend er jo ikke så rart.

Og i tilfellet der vi er i dyplenke-modus så er det viktig at vi har noe annet å vise dem for vi kan ikke vise siden som den er når 'legg til'-knapper blir trykket automagisk det skjer en masse fargeendringer og venting på svar i tur og orden. Det vil bare se rart ut for brukeren. Er derfor vi må vise dem noe annet istedenfor.

Alternativt trenger man kanskje ikke å ha skeleton på hele siden og kan heller vise enten spinner eller skeletons istendenfor actionBarene i API-søket (og lagt til API). For det er jo der at ting vil endre seg.

**Comment by Albertlarsen** [comment]
Ja det kan være der uansett hvor man kommer fra egentlig, vi må bare legge til noe kode som indikerer at delegationCheck er gjort på alle api-er i urlen som Skeleton kan lytte til.

Kan være smart å ikke ha skeleton på hele siden, vil jo bli mindre utvikling knyttet til å skissere hele sider. Spørsmålet er vel bare om det vil bli tydelig nok for brukeren at siden faktisk holder på å laste. Men jeg er egentlig med på å prøve det ut så kan vi se hvordan det funker i AT og hvor lange laste-tidene i der vil bli osv
