### ISSUE TITLE
Create alternative login for localtest to login locally

### ISSUE THREAD

**Issue by AlbyIsCoding** [Altinn/altinn-access-management-frontend#647]
### Description

Tasks for data setup:
- [ ] Create a simple view that contains a dropdown list over different users, preferably based on the BFF mock data
- [ ] Make that view only show up when enabled in appsettings.development
- [ ] Make cookie based on response from this endpoint and change the url based on what's chosen in the views: 
`https://altinn-testtools-token-generator.azurewebsites.net/api/GetEnterpriseToken?env=at22&scopes=altinn:resourceregistry/resource.admin&org=ttd&orgNo=991825827&ttl=36000`
Cookie that's going to be made:
![Image](https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/c4659138-1125-43ba-9121-c92df80095fe)
- [ ] Make BFF choose environment based on what's chosen in the dropdown list (if possible).

Refinement:

- We will not be able to see backend integration when working from other places than the office

**Comment by Albertlarsen** [comment]
On hold until we get the new Digdir computers.

**Comment by allinox** [comment]
Fixed with new local setup (AT22-hybrid method)
