### ISSUE TITLE
Move API search to BFF

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#685]
### Description

Right now, the logic used for searching and filtering APIs lie in the frontend code - placed there when we had no BFF and therefore no backend to support such logic. This is not ideal since it clutters up the code and the redux slice significantly and now that we do have a BFF, we want to move our logic back there instead.

Tasks:

- [x] Implement search logic in the BFF, transforming the current GetMaskinportenSchema endpoint
- [x] Implement the rtk query for the search
- [x] Write Unit tests
- [x] Make maskinportenschema search query work in the frontend
- [x] Fix bug in code when removing chosenApis from searchResults
- [x] Ensure error object is serialized correctly
- [x] Make GetResourceOwnerList in BFF
- [x] Write tests for GetResourceOwnerList
- [x] Write rtk query for GetResourceOwners
- [x] Connect MaskinportenSearch query with chosen resourceOwners in filter

### Acceptance Criterias

**Scenario:** Doing a search for apis on ChooseApiPage
Given it has been searched for 'fr'
When the search is done loading
Then the only APIs showing should be the ones that have 'fr' in their title.

**Scenario:** The options of organizations in the filter corresponds to the API list
When the Filter is done loading 
Then the only options that you can filter on are the ones that also have APIs in the list.

**Scenario:** Filtering organizations on ChooseApiPage
Given one or more organizations is chosen in the filter
When the UI is done loading
Then the only APIs showing should be the ones that has the chosen organizations

**Comment by Albertlarsen** [comment]
Til diskusjon i teknisk refinement: Snakke å liste ut ressurseiere basert på ressurstypene til disse eierne.
