### ISSUE TITLE
Fix the error page

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#689]
### Description

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/f91b0076-79de-4d02-884c-01a59150ce92)

Right now the NotFoundPage is made to work as the error page presented to the user when they try to access a page that does not exist (status code 404) However, in reality, it is triggered on multiple error-occasions as a general error-page, which not only makes the display of the text misleading but because the way the page is currently coded it will fail if the expected error message does not fit the 404-error.

This needs to be fixed, preferably quickly to help facilitate debugging such as in #688

### Tasks:
- [x] Make NotFoundPage into a catch-all Error page, with case-based content based on status code
- [x] Fix bug in error page that causes it to fail into a BOD (Bluescreen Of Death) whenever a different code than 404 is triggered

**Comment by allinox** [comment]
@Randiabs og @hannekristin 

Denne gjør minimale endringer på selve Page not Found designet som dere satte opp tidligere. Som nå ser slikt ut:
![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/d9be6f97-99cd-4e41-a922-34546198fc10)

Eneste som er gjort her er å bytte til å bruke Designsystemet sine Typografi-komponenter som Heading og Paragraph og å legge til tidspunktet feilen oppstod

Det som er nytt er at jeg har laget en mer generisk feilmeldingsside som skal vises når noe uforutsett går feil på siden, i tilfellet hvor vi ikke har noen statuskode (som 404 for Page not Found)
Jeg satte opp denne siden kjapt fordi den blokkerte debuggingen av en bug vi nå har i Single-rightssiden så jeg pusha det bare ut fort for at vi nå kan jobbe med å løse buggen.
Nå som det er gjort er det bare å si ifra om dere ønsker endringer på den, så kan jeg fikse det senere.
Pr nå ser den generiske feilsiden slik ut:
![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/b120bf35-ff27-494c-a86b-91bf2a53ad14)

**Comment by hannekristin** [comment]
Ser greit ut. Lukker saken
