### ISSUE TITLE
API endpoint allowing to create a resource with capital letters in the resource ID

### ISSUE THREAD

**Issue by acn-Sneha** [Altinn/altinn-access-management-frontend#701]
Looks like API endpoint POST/{{EnvUrl}}/resourceregistry/api/v1/resource allowing to create a resource with capital letters in the resource ID

![Image](https://github.com/Altinn/altinn-access-management-frontend/assets/113685460/1d428721-2043-443d-834c-d840486c4e34)
```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-studio/issues/12165
- [x] Do not allow creation of resources with uppercase letters
```

**Comment by mgunnerud** [comment]
Fikset i https://github.com/Altinn/altinn-resource-registry/pull/390
