### ISSUE TITLE
Handle unauthorized user on delegationCheck

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#711]
### Description of the bug

A user can potentially reach the single-rights page while representing a party they do not have the right to delegate single-rights for. If they do, they will not be able to delegate and will be stopped by the delegation-check, which is reasonable.

However, the error displayed to them is that of a technical error and they are prompted to try again or contact the service desk.

What should instead happen is that they should receive a message explaining the true situation to them.

Suggestion of message content:
"Du kan ikke delegere tjenester for valgt aktør. Dersom du mente å delegere på vegne av noen andre, vennligst gå til profilen og velg denne aktøren fra avgiverlisten."

### To Do

- [x] Catch the unauthorized response provided by the backend in the BFF and propagate it up to frontend
- [x] Add a new error-scenario that presents an Unauthorized code in place of the add-button and a message inside the actionBar (alert) that informs the user that they are not authorized to perform delegations on behalf of their current party.

### Current view

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/a4dc0f52-8e72-4a78-a69a-79f11cc39018)

**Comment by allinox** [comment]
Oppdaget dette caset nå. Hva synes dere om forslaget til formulering på meldingen @hannekristin @Randiabs?

**Comment by hannekristin** [comment]
@allinox Tenker du det som en tekst i det bildet som ligger i tasken her?

**Comment by hannekristin** [comment]
Jeg bare lurte på om du mente bildet her som er en teknisk feil som har oppstått, men ok. Jeg synes det er et litt søkt eksempel at bruker er inne på feil aktør og at det er årsaken. Ser ikke noe grunn til endre opprinnelig tekst. 
![image](https://github.com/Altinn/altinn-access-management-frontend/assets/103100644/4114ee4c-c25d-4c86-889b-3967df1ff905)

**Comment by allinox** [comment]
@hannekristin 
Den opprinnelige teksten skal ikke endres - det vil fremdeles være et case, det er bare at dette med Unauthorized kommer som et nytt case i tillegg.
Vi vet at det kan skje fordi det har allerede skjedd med meg nemlig.
Man kan f.eks. havne i den pga bookmarks eller ved å stå på delegerings-siden for lenge så man blir logget ut (og så velge å representere en annen person eller organisasjon som man ikke har lov til å delegere for)

**Comment by hannekristin** [comment]
Fortsatt et lite sannsynlig scenario, men det er bare å legge inn feilmeldingen. Får ikke testet det, men lukker saken
