### ISSUE TITLE
Develop end-to-end tests for single right delegation in Playwright

### ISSUE THREAD

**Issue by sneha-sirure** [Altinn/altinn-access-management-frontend#725]
### **Description**
This is a test issue created to develope cypress test for the whole functionality of single right delegations which is implemented in A3

### **Test cases to be covered**
Test cases which are covered in cypress listed here. Test cases should cover end-to-end testing. Both positive and negative tests should be listed

**1. DAGL/HADM delegable (without having the actual resource access themselves)** 

**On behalf of Org :** 
- [x] User A who is DAGL/HADM for org delegates resources/Altinn 3 app/Altinn 2 services to User B. 
- [x] User A who is DAGL/HADM for org delegates resources/Altinn 3 app/Altinn 2 services services to Org B. 
- [ ] User A who is DAGL/HADM for org delegates Resource of type MaskinPorten schema from org to org. 
- [x] DAGL/HADM do not have rights to delegate Altinn2 to org Y , but has the rights to delegate same service after delegating sens role to himself
- [ ] Negative : delegation of a Resource of type MaskinPorten schema from an org to EC user

**2. ADMAI + Role access to the delegation resource**

**On behalf of Org :** 
- [ ] UserA who is DAGL for mainUnitX  delegates ADMAI and role to orgY. DAGL for orgY logged in and represent subunit X which is subunit of main unit X can delegates Resources, Altinn 3 App and Altinn 2 services to user Z
- [ ] UserA who is DAGL for mainUnitX  delegates ADMAI and role to orgY. DAGL for orgY can delegate sResources, Altinn 3 App and Altinn 2 services to Org B
- [ ] UserA who is DAGL and has access to Resources, delegates ADMAI + SISKD for delegating Resources, Altinn 3 app and Altinn 2 services to EC_User 
- [ ] Delegation of a resource  of type MaskinPorten schema from Org to an org

**On behalf of person :** 
- [ ] User E who has got ADMAI + SISKD role from main User (User G) and User G tries to login and instantiate Resource on behalf of user E

**3. ADMAI + Single right access to the delegation resource**

**On behalf of person :** 
- [ ] MainunitX delegates resources, Altinn 3 App, Altinn2 services and ADMAI role to userA, UserA can represent subUnitY(which is sub unit of X) and delegate resource/Altinn 2 services/ Altinn 3 App to user B and now user B logged in and instantiate resources on behalf of subunit Y 
- [ ] User A who is DAGL for mainUnitX  delegates ADMAI and resource/Altinn 2 services/ Altinn 3 App to orgY. DAGL for orgY logged in and represent subunit X which is subunit of main unit X can delegate Resources to Org B 
- [ ] UserA who is DAGL for mainUnitX  delegates ADMAI and resource/Altinn 2 services/ Altinn 3 App to orgY. DAGL for orgY can delegate resource/Altinn 2 services/ Altinn 3 App to EC_User

**On behalf of person :** 
- [ ] User E who has got ADMAI + resource/Altinn 2 services/ Altinn 3 App role from main User (User G) and User G tries to login and instantiate Resource on behalf of user E

**4. HADM/ADMAI + Non-delegable resource/app/service (Negative tests)**

- [ ] Delegation of a  Non-delegable resource/ Altinn 2 services from org to a Person
- [ ] Delegation of a  Non-delegable resource/ Altinn 2 services from org to a Org
- [ ] Delegation of a resource  of type MaskinPorten schema from Org to Org

**5. User (without HADM/ADMAI) + Delegable resource (Negative tests)**

- [ ] Delegation of a  delegable resource/Altinn 2 services/ Altinn 3 App from org to a Person
- [ ] Delegation of a  delegable resource/Altinn 2 services/ Altinn 3 App from org to a Org
- [ ] Negative : Delegation of a resource  of type MaskinPorten schema from Org to Org

**Comment by acn-Sneha** [comment]
@rtafj @jonkjetiloye Da ser jeg Det som vi krever er på plass og kan fortsatte med utvikling testene som var på pause, men spørsmål at siden vi skal bruke playwright i fremtid som vi har bestemt da tenker jeg at jeg skal først sette opp playwright for å kjøre testene mot AT og da skal jeg utvikle de enkeltrettigheter testcasene i playwright istedet skal fortsatt å utvikle i cypress hvis det gir mening? Bare si fra hva tenker dere om det?

**Comment by Albertlarsen** [comment]
Jeg synes det bare er å teste ut Playwright om du har lyst til det 😁
