### ISSUE TITLE
Cypress tests are failing due to change in language takes longer time to get reflected

### ISSUE THREAD

**Issue by acn-Sneha** [Altinn/altinn-access-management-frontend#733]
Our cypress tests has pre-requisite : The choosen language should always be norwegian before it starts to run all tests but I see changing language takes 20 minutes to get reflected in altinn 3 which might be problematic for us to run cypress tests

**Comment by acn-Sneha** [comment]
@Albertlarsen raised a bug as we discussed.

**Comment by Albertlarsen** [comment]
@acn-Sneha Final fix of this was just made and for me language change seems to work instantly now. Can you verify that it works as expected?
