### ISSUE TITLE
Make filter work in 400% zoom

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#785]
WCAG requires all functionality to be visible on screen, even with 400% zoom.
The problem is that this activates mobile screen rendering (unless you're on an extremely wide screen) This makes the filter open in a modal that is adjusted for tall screens, not laptops.

I am unsure exactly how to fix this so that it works both on mobile and 400% zoom. Perhaps we will have to move the apply and reset buttons so they are side by side?

<img width="1505" alt="image" src="https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/dff3563b-9b83-4820-8571-0a065b376e0e">

**Comment by Albertlarsen** [comment]
Closing this because it's merged
