### ISSUE TITLE
Should inform user that no services is chosen

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#851]
### Description of the bug

When no services are chosen in single rights we should inform the user about that and display navigation button back to 

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/2cb5b19e-f6e8-4504-94c1-9be875bfdab2)

Proposed solution:

![Image](https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/e3cd0e8f-f6eb-416d-b690-b41f3c167deb)

### Steps To Reproduce

When no services are chosen in single rights we should inform the user about that and display navigation button back to single rights overview

**Comment by Albertlarsen** [comment]
@jonkjetiloye @rtafj

Trenger input fra dere på den her

**Comment by rtafj** [comment]
@Albertlarsen @jonkjetiloye Har sett på proposed solution sammen med UX, og det ser bra ut.

**Comment by Albertlarsen** [comment]
@rtafj så bra, jeg legger til slik at den blir litt mer diskret med å blå farge i stedet for gul også fikser jeg opp i skrivefeil i tillegg

**Comment by rtafj** [comment]
@Albertlarsen  - vil denne meldingen også dekke scenario der man har lagt til en tjeneste, og deretter fjerner alle actions/operasjoner? Siden ser slik ut i dette caset;
![image](https://github.com/Altinn/altinn-access-management-frontend/assets/36295493/71832e4b-864d-4ead-b9ea-8acc1ced8955)

**Comment by Albertlarsen** [comment]
@rtafj Nei det vil ikke dekke det. De må trykke på fjern på ressursen før den vises
