### ISSUE TITLE
Unhandled exception occured while processing the request in BFF

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#853]
### Description of the bug

Seems to have happened with one of our latest merges with main.

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/31471142/7fd5ccab-eb49-4ca9-a055-23285da2caee)

### Steps To Reproduce

1. Pull latest main and run BFF

**Comment by allinox** [comment]
@Albertlarsen Is this still a problem in your local setup?
(It isn@t in mine you see 😅)

**Comment by Albertlarsen** [comment]
I think it is but let's have a look at it tomorrow 😊

**Comment by Albertlarsen** [comment]
Will be fixed when pulling latest changes in LocalTest in branch feature/accessmanagement-subdomain
