### ISSUE TITLE
Tilbakemeldinger på språk-feil etter TT02 deploy

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management-frontend#855]
### Description of the bug

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/40996230/24e12cd3-35d1-4a35-b069-73c058db1c99)

### Steps To Reproduce

1. Login with user having nynorsk as selected language
2. Delegate service where the user is missing needed roles

### Additional Information

Slack:
https://altinn.slack.com/archives/C05P3AEP3EX/p1713167254042949

**Comment by allinox** [comment]
@Albertlarsen 
Can we close this?

**Comment by Albertlarsen** [comment]
@allinox yes
