### ISSUE TITLE
Can still delegate even when "Access" is deselected on A3 services

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#856]
### Description of the bug

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/1f9d363c-9ce8-4a3c-8f16-db59aa56ebda)

Normally, the fact that all chips are deselected would disable the button to trigger delegations. However, in the case of A3 apps, this chip is currently not directly linked to the actions for delegation, but is instead a catch all to enable delegation of all possible actions.

The error here is that the button for delegation should be disabled when this chip is deselected and there are no other services with selected chips. It is likely fixed by setting the selected attribute on all actions on the service to false/true on the service whenever this chip is deselected/selected

### Steps To Reproduce

1. Go to the single rights page
2. Choose an A3 app
3. Deselect "Tilgang" chip
4. Observe that you can still press "Fullfør delegering"

**Comment by Albertlarsen** [comment]
Proposed fix: Legger til samle-chipen "tilgang" i den faktiske lista over actions som er koblet til koden for å disable "Fullfør delegering"-knappen.

**Comment by Albertlarsen** [comment]
Refined proposed fix: Legg til rightskey-felt i rightKeyen som vi toggler på i stedet
