### ISSUE TITLE
Order Orgs in filter alphabetically

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#858]
![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/64fbf996-d684-448e-a45a-17f35cc85bde)

The org list in the filter is now unordered, making it hard to find anything without searching and generally looks a bit messy.
Organize these alphabetically in the BFF

**Comment by Albertlarsen** [comment]
Should we close this or set it to test @allinox ?

**Comment by Albertlarsen** [comment]
Nah I checked it now after prod and works really well, so closing it seems fine 😊
