### ISSUE TITLE
Feil i tekst, mangler rettigheter

### ISSUE THREAD

**Issue by Randiabs** [Altinn/altinn-access-management-frontend#873]
Når man prøver og gi rettigheter som man selv ikke har kommer følgende tekst opp i alerten , men denne er feil: 

![Image](https://github.com/Altinn/altinn-access-management/assets/94835837/7e7bcb64-f146-4c84-bb83-72a0b8a26ad4)

Men den korrekte teksten er: 

![Image](https://github.com/Altinn/altinn-access-management/assets/94835837/85af5cb6-83d0-4627-8457-ef8fcac93acd)

**Comment by Albertlarsen** [comment]
Hei, grunnen til at denne feilmeldingen kommer er fordi error-koden vi får fra backend er MissingRoleAccess. De tekstene dere viser til her kommer opp når error-koden er MissingDelegationAccess.

@Randiabs  Jeg foreslår at dere finner nye tekster som du vil skal komme opp når error-koden er MissingRoleAccess eller tar opp med backend at error-koden de returnerer er feil 😄

**Comment by hannekristin** [comment]
@allinox Kan du se på denne saken? Det holder at vi legger inn en tekst som er generell og dekker alle typer av manglende tilgang. Se bildet over

**Comment by allinox** [comment]
@hannekristin 
Det kan vi fikse 👍
Regner med at det er tittelen og beskrivelses-teksten i alerten det er snakk om her?

**Comment by hannekristin** [comment]
Det stemmer @allinox
